### ISSUE TITLE
Informations about this plugin

### ISSUE THREAD

**Issue by heruan** [aurelia/i18n#1]
I'm working on a SPA which requires I18N support, and I'm looking at `polyglot.js`, `Jed` and `i18next` libraries. Since I'm using the Aurelia framework, I found this repository and I wonder if an official I18N plugin for Aurelia is coming in the next few weeks!

**Comment by zewa666** [comment]
Hi there,

this official repo will be based on i18next. It's currently in the final phase. You can see the pre-work at https://github.com/zewa666/aurelia-i18next

Hope to get it live by next week, there is only one more important thing missing.
