### ISSUE TITLE
Shared DateTimeFormat

### ISSUE THREAD

**Issue by AdamWillden** [aurelia/i18n#100]
I was going to request that we had  away to 'share' the dateFormatter as I suspect it would improve performance. I then looked at the code and noticed the extra dateFormat function which can do just that.

However I'm not a fan of how you'd need to specify the formatter 

`<div title.bind="date | df:null:null:dateFormatter"></div>`

Could this:
```js
  toView(value, formatOptions, locale, dateFormat) {
    let df = dateFormat || this.service.df(formatOptions, locale || this.service.getLocale());

    return df.format(value);
  }
```
become this:
```js
  toView(value, dfOrOptions, locale) {
    if (dfOrOptions && (typeof dfOrOptions.format === 'function') {
      return dfOrOptions.format(value);
    } else {
      return this.service.df(dfOrOptions, locale || this.service.getLocale());
    }
  }
```

Or for backward compatability ideally with a depreciation warning
```js
  toView(value, dfOrOptions, locale, df) {
    if (dfOrOptions && (typeof dfOrOptions.format === 'function') {
      return dfOrOptions.format(value);
    } else if(df) {
      // For BC wth some depreciation warning notice here
      return df.format(value);
    } else {
      return this.service.df(dfOrOptions, locale || this.service.getLocale());
    }
  }
```

**Comment by EisenbergEffect** [comment]
@zewa666 This seems like a reasonable request. What do you think?

**Comment by zewa666** [comment]
@EisenbergEffect absolutely. @AdamWillden I would love to see a PR for this.

**Comment by AdamWillden** [comment]
I'll try to get to it. Although it's a small change I'm closing in on a deadline that I've no hope in hell of meeting! All my brains must focus.

**Comment by AdamWillden** [comment]
Incidentally how would I do the depreciation warning?

**Comment by zewa666** [comment]
Yes the deprecation warning would be certainly nice, given we're now officially in beta. @EisenbergEffect could you chime in on this one and provide an example? Is a special case of console.log enough?

**Comment by zewa666** [comment]
@AdamWillden ok i've created the patch and added a console.warn as deprecation notice. Thanks for the support, good hint, feels much nicer now.

**Comment by AdamWillden** [comment]
Awesome, thank you!

**Comment by AdamWillden** [comment]
Ah yes console warn looks good and is what is used here: https://github.com/aurelia/metadata/blob/master/src/deprecated.js
