### ISSUE TITLE
DateTimeValueConverter shows 01/01/1970 for null values

### ISSUE THREAD

**Issue by AdamWillden** [aurelia/i18n#101]
![image](https://cloud.githubusercontent.com/assets/4629144/14742923/91f94cd8-0896-11e6-876e-1c7b64cdefdc.png)

Is it reasonable to add a check whereby if the value is `null` or `undefined` we simply return that value instead of trying to format it to 1970?

It works perfectly for numeric tick values by the way so I would **not** want to limit it to date values only.

**Comment by zewa666** [comment]
good idea. I've created a patch fixing that, I'm just not sure about the last sentence. What do you exactly mean with numeric ticks? Could you give me an example?

**Comment by AdamWillden** [comment]
@zewa666 I stumbled across this by accident initially as I get all my date times as JavaScript ticks from the server. Best shown by [an example](http://jsfiddle.net/Lqz3efy3/).

I meant I didn't want a patch that was `if (!(value instanceof Date)) return value;` as that'd screw up the fact it handles numbers as ticks :-)

**However**, looking at your patch I think it'd be better if it explicitly checked `if (value === null || typeof value === 'undefined') return value;` as 0 would result in "0" and not a formatted 1970 date! Ha.

If you need more clarification let me know. I'm not always the best at explaining things!

**Comment by AdamWillden** [comment]
Thank you by the way :-)

**Comment by zewa666** [comment]
ahh good catch :+1: . Ok fixed that one as well. Think we're good to go now

**Comment by AdamWillden** [comment]
Ah nice yeah,
