### ISSUE TITLE
t[append/prepend] problem

### ISSUE THREAD

**Issue by atticushome** [aurelia/i18n#111]
Hi!

If I use it like this `<label  t="[append]label"><input type="radio" model.bind="true" checked.bind="checked"></label>` checked.bind stops working.
Am I doing something wrong or is it not supposed to work like this?

Thanks!

**Comment by zewa666** [comment]
Well ... yes its supposed to work, and no it does not do that currently :)
Tbh when this feature was designed that use-case wasn't kept in mind, so thanks for pointing that out.

**Comment by atticushome** [comment]
Nice, thanks for a quick feedback.

**Comment by zewa666** [comment]
@atticushome should be fixed with the latest commit, next Tuesday the new version should be available and ready to be tested

**Comment by EisenbergEffect** [comment]
Closing since the fix was merged.
