### ISSUE TITLE
Passing parameters with i18n.tr is not working

### ISSUE THREAD

**Issue by avizcaino-newuibcn** [aurelia/i18n#117]
Hi, I'm defining a translation key such as `"action-executed" : "Action __act__ executed"` and then calling the translation with `i18n.tr("action-executed", {act: 'delete'})`.

I'm expecting `"Action delete executed"` as a result, but instead, I'm receiving `"Action __act__ executed"`. I've tried to debug this issue but I'm unable to find where the problem is.

I'm using right now aurelia-i18n version 0.5.1.

The weird thing is that this is working if I'm using the i18n converter in a template `${'action-executed' | t: {'act': 'delete'}`.

**Comment by Mordred** [comment]
I think that default interpolation is '{{' and '}}'. Can you try `Action {{act}} executed`?

**Comment by avizcaino-newuibcn** [comment]
Yep, that worked. But this has changed right? I'm pretty sure that it was working in older versions with the format __param__

**Comment by zewa666** [comment]
@avizcaino-newuibcn yep this has changed with the upgrade to i18next v2, see here https://github.com/aurelia/i18n#migration-to-new-i18next-version
