### ISSUE TITLE
Webpack: extract translation example

### ISSUE THREAD

**Issue by 7Pass** [aurelia/i18n#127]
I configured my webpack to automatically extract translatable texts, since aurelia-i18n does not have a scanner (yet), in case anyone is interested: https://gist.github.com/7Pass/99c72117a836daa516137601f296d884

**Comment by EisenbergEffect** [comment]
Looks awesome!
Would you be interested in working this into a Webpack-independent library? That's something we could then use across all build systems to help out the community.

**Comment by EisenbergEffect** [comment]
@zewa666 I know you were thinking about or working on something like this. This seems like a good opportunity to help move that effort forward.

**Comment by 7Pass** [comment]
The config I'm using cannot extract translations using `TValueConverter` yet as `i18next-scanner` does not support that case. I guess I can create a small npm package to make it easy to install.

**Comment by EisenbergEffect** [comment]
Maybe just start with a new Gist that's refactored to be less webpack-specific. Then we can open up some conversation with @zewa666 on it and see where this leads?

**Comment by 7Pass** [comment]
@zewa666: I've created https://gist.github.com/7Pass/96c6f3dacc9931d9bcdcb4d5bc68c2d8 so that the script can be used outside webpack. Next step would be how to extract values translated with `TValueConverter`. I have not checked case with attribute prefixes though, but that should be a simple step after the current extraction to separate extracted string into individual strings for every property, then remove the property name.

**Comment by zewa666** [comment]
@7Pass great work. That was something on my todo list for long time. Is that somehow comparable to https://github.com/i18next/i18next-parser? I would personally prefer to stick to the original repo and share their functionality but if that doesn't work maybe going on with your solution is the way to go.
May I ask you to test 18next-parser and see how that stacks up against your solution?

**Comment by zewa666** [comment]
Any updates on this one @7Pass ?

**Comment by 7Pass** [comment]
@zewa666 I have not tried https://github.com/i18next/i18next-parser but it looks good. I'm more used toward using Gettext, so i18next was not my best choice. Unfortunately, my project at work stays with Gettext so I cannot invest into i18next just yet. I'll close this issue as I do not have further contribution to provide.

**Comment by zewa666** [comment]
Thats quite unfortunate, nevertheless thanks for your time. Btw Id love to know how we could make Aurelia i18n interesting for you as well. Would something like https://github.com/i18next/i18next-gettext-converter help?

**Comment by 7Pass** [comment]
It has nothing to do with Aurelia at all. It's actually from i18next. i18next does support gettext, but one important part of gettext is support for plural forms, meaning having the source in English and provide both singular and plural form in the source, and let a tool extract it out. Most users tried i18next has resorted to using key based fallback instead, going away from gettext. Our application is quite large, and we'd prefer to let the text not be translated rather than missing texts.

From my experience, key based translations works OK for small application, when translations are considered done the moment a version is released. Our version of 4 years ago already have almost 100k strings for translations, for 6 languages in additional to English, so translation is an ongoing effort instead. Our customers can then update the translations whenever they want, which is really useful for translators as they can immediate see the translations that they have just contributed.
