### ISSUE TITLE
Can we have a new release with dependent modules in aurelia/build/resources?

### ISSUE THREAD

**Issue by Jenselme** [aurelia/i18n#128]
Hi,

In the process of updating the webpack loader, I found out that even if dependent modules are in aurelia/build/resources (as required by the new version) in master thanks to #121, the latest release doesn't have that. Can you make a new one to ease the update process?

**Comment by EisenbergEffect** [comment]
We will have a batch of new releases on Tuesday.

**Comment by Jenselme** [comment]
@EisenbergEffect OK, thanks.
