### ISSUE TITLE
Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/i18n#13]
Unhandled promise rejection TypeError: Cannot read property 'forEach' of undefined
    at http://localhost:9000/jspm_packages/github/aurelia/i18n@0.2.0/index.js:89:43

line 89 is this line: https://github.com/aurelia/i18n/blob/master/src/index.js#L35

the `attributes` property is undefined.

**Comment by JeroenVinke** [comment]
I didn't need any attributes so I removed it from the options. this caused the error because it expects any empty array

```
instance.setup({
    resGetPath: "resources/locale/__lng__/__ns__.json",
    lng: "nl",
    attributes: [], <-- I didn't have this anymore
    getAsync: true,
    sendMissing: false,
    fallbackLng: "nl",
    debug: false
});
```

**Comment by zewa666** [comment]
ok thx for the hint, like your PR, lets continue the discussion over there
