### ISSUE TITLE
Enhancement: Load namespaces dynamically upon page activation using a decorator

### ISSUE THREAD

**Issue by AdamWillden** [aurelia/i18n#134]
**I'm submitting a feature request**

Provide a decorator to load a namespace upon initial activation. Not sure how common this is but I have my namespaces set up matching my main navigation. 

Previously I was loading all files on application load. I'm about to add this to all my activate calls to load them dynamically as required:

```js
new Promise((resolve) => {
  this.i18n.i18next.loadNamespaces('my-namespace', () => resolve());
});
```

It struck me that a decorator could probably do this quite nicely `@loadTranslationNs('my-namespace')`. I'm trying to do it now as I've not made a decorator before, when I'm done I'll share the code.

Not sure if this is something we want in the core or if it'll just bloat. I'm not precious about it.

**Comment by AdamWillden** [comment]
This code works:

```js
import i18next from 'i18next';

export function loadTranslationNs(translationNs) {
  return function(target, key, descriptor) {
    if (typeof descriptor.value !== 'function' && key !== 'activate') {
      throw new SyntaxError('Only activate functions can have the loadTranslationNs decorator');
    }

    return {
      ...descriptor,
      value: function loadTranslationNsWrapper() {
        let promise = new Promise(resolve => i18next.loadNamespaces(translationNs, () => resolve()));

        let retValIsPromise = false;
        let retVal = descriptor.value.apply(this, arguments);
        if (typeof retVal === 'object' && typeof retVal.then === 'function') {
          retValIsPromise = true;
        }

        if (retValIsPromise) {
          return Promise.all([promise, retVal]);
        }

        return promise;
      }
    };
  };
}

export default loadTranslationNs;
```

As a side note. I wasn't sure how to handle dependency injection with decorators to get an `aurelia-i18n` instance. I'm not sure it's even possible. I realised that i18next is effectively a singleton so injected that directly.

The issue I then faced (because this is in my own codebase) is that I had to create a direct dependency upon i18next which previously I didn't have (I had to run `jspm install i18next`). Would it make sense to submit a PR to statically expose `i18next` on the `I18N` object so I can do this in my codebase:

```js
import {I18N} from 'aurelia-i18n'; // change 1/2

export function loadTranslationNs(translationNs) {
  return function(target, key, descriptor) {
    if (typeof descriptor.value !== 'function' && key !== 'activate') {
      throw new SyntaxError('Only activate functions can have the loadTranslationNs decorator');
    }

    return {
      ...descriptor,
      value: function loadTranslationNsWrapper() {
        let promise = new Promise(resolve => I18N.i18next.loadNamespaces(translationNs, () => resolve())); // change 2/2 (I18N.i18next)

        let retValIsPromise = false;
        let retVal = descriptor.value.apply(this, arguments);
        if (typeof retVal === 'object' && typeof retVal.then === 'function') {
          retValIsPromise = true;
        }

        if (retValIsPromise) {
          return Promise.all([promise, retVal]);
        }

        return promise;
      }
    };
  };
}

export default loadTranslationNs;
```

**Comment by AdamWillden** [comment]
I suspect the decorator could do with placing a `Symbol` on the target to save the state (i.e. it has been loaded so don't load it again on the next activation). 

Also I don't handle the case where it might fail to load for whatever reason.

**Comment by EisenbergEffect** [comment]
@AdamWillden I'm not sure I would consider this a good practice. The decorator you have hear doesn't really decorate the target. It's more of a side-effect decorator. I would really re-consider this approach. I don't think it's something we would put in the framework, regardless.

**Comment by AdamWillden** [comment]
@EisenbergEffect I get what you mean, it's not adding metadata. I'll keep this in mind.

If I were to continue with this idea I guess the better course of actions would be to decorate the class by adding a symbol to the target assigned with the namespace to load. If it were possible I'd then look for that decoration that as a step during activation/binding and handle it appropriately.

I considered a `addPreActivateStep` but that doesn't seem to have access to the model instance. I'm not sure how I'd do that part at the moment.

I know I could inject something and call a method on that during activation but I'd prefer something more 'separated'.
