### ISSUE TITLE
instance.i18next property is undefined after loading aurelia-i18n plugin

### ISSUE THREAD

**Issue by kevmeister68** [aurelia/i18n#137]
**I'm submitting a bug report**

* **Library Version:**
Aurelia-i18n-1.0.0rc.1.0.0

**Please tell us about your environment:**
* **Operating System:**
Windows 7

* **Node Version:**
0.12.2 ???

* **NPM Version:**
3.8.9

* **JSPM OR Webpack AND Version**
RequireJS 2.1.20

* **Browser:**
IE 11

* **Language:**
TypeScript 1.7, Visual Studio 2015 Update 3

**Current behavior:**

Am loading the Aurelia-i18n plugin per the documentation, using the i18next-xhr-backend as the backend. In the then( ) functor I go to assign the backend object as follows

     .plugin( "aurelia-i18n", ( instance ) => {

         instance.i18next.use( Backend );   <-- i18next is undefined here.

However, there is an instance.i18nextDefered object which is defined.

**Expected/desired behavior:**

instance.i18next should not be undefined - very likely related to environment.

**Comment by zewa666** [comment]
@kevmeister68 the underlying i18next service needs to be setup as well, which results in a promise returned. In order to be at proper timing you'd have to use the `i18nextReady` function to get hold of the init promise.

```
 .plugin( "aurelia-i18n", ( instance ) => {
     instance.i18nextReady().then( (srv) => srv.use( Backend ));
```

**Comment by Robbe64** [comment]
Run into the same issue. Please update the doc: http://aurelia.io/hub.html#/doc/article/aurelia/i18n/latest/i18n-with-aurelia/3

**Comment by zewa666** [comment]
I'm not sure why that happened for you, the original issue was fixed in the meantime. So it must be something related to your app trying to fetch data eagerly before the service is initiated. Typically the described approach in the docs should work.

Can you try to create a minimal example, reproducing the problem and open a new issue so we can take a look at it?

**Comment by Robbe64** [comment]
I got this propblem when I tried to use the in i18n bundeled backend. But I didn't got it running with the workaround described here.
I switched to i18next-xhr-backend and now it works without the workaround.

Don't know what's the reason for the problem with the bundeled backend but didn't tried again.

**Comment by Xceno** [comment]
Just a quick heads up. I had the same issue and this was the problem:

`au install` updated the `aurelia.json` file like this:

```
  {
    "name": "i18next",
    "main": "i18next",
    "path": "../node_modules/i18next/dist/umd"
  },
  {
    "name": "i18next-xhr-backend",
    "main": "./index.js",
    "path": "../node_modules/i18next-xhr-backend/dist/umd"
  },
  {
    "name": "i18next-browser-languagedetector",
    "main": "./index.js",
    "path": "../node_modules/i18next-browser-languagedetector"
  }
```

Which produces the exact same error as described above.
I fixed it by adjusting it like this:

```
  {
    "name": "i18next",
    "main": "i18next",
    "path": "../node_modules/i18next/dist/umd"
  },
  {
    "name": "i18next-xhr-backend",
    "main": "i18nextXHRBackend",
    "path": "../node_modules/i18next-xhr-backend/dist/umd"
  },
  {
    "name": "i18next-browser-languagedetector",
    "main": "i18nextBrowserLanguageDetector",
    "path":   "../node_modules/i18next-browser-languagedetector/dist/umd"
  }
```
