### ISSUE TITLE
dist\aurelia-i18n.ts(1,21): error TS2307: Cannot find module 'i18next'.

### ISSUE THREAD

**Issue by gravsten** [aurelia/i18n#139]
**I'm submitting a bug report**
* **Library Version:**
1.0 (from Git 'master')
* **Operating System:**
Windows 8.1
* **Node Version:**
6.3.0
* **NPM Version:**
3.10.3
* **JSPM OR Webpack AND Version**
JSPM 0.16.41
* **Language:**
TypeScript

**Current behavior:**
When I run "gulp build-ts" or "gulp build-dts", I get an error TS2307 (Cannot find module 'i18next'.)
"gulp build" works fine, though.

**Expected/desired behavior:**
Either of those commands should produce the desired "aurelia-i18n.ts", respectively "aurelia-i18n.d.ts".

For reference, I have installed all dependencies:
jspm install npm:i18next-xhr-backend
typings install dt~i18next --global --save
... and copy to .\typings :
https://raw.githubusercontent.com/aurelia/i18n/master/doc/i18next-xhr-backend.d.ts

**Comment by tipa** [comment]
having the same problem. Is this going to be resolved?

**Comment by zewa666** [comment]
yes just take a look at the recent blog post which describes what you need to do for TS and the CLI. The same kinda applies for JSPM/Webpack. Its mostly an issue with installing the proper dts files

**Comment by tipa** [comment]
After installing the new d.ts-file via `typings install dt~i18next --save --global  
` get the following error now: `typings\modules\aurelia-i18n\index.d.ts(4,8): error TS1192: Module ''i18next'' has no default export.`

**Comment by atsu85** [comment]
@tipa, see [my comment](https://github.com/aurelia/i18n/issues/56#issuecomment-231227926)
