### ISSUE TITLE
context remain

### ISSUE THREAD

**Issue by hadrienl** [aurelia/i18n#143]
**I'm submitting a bug report**
- **Library Version:**
  1.0.0-rc.1.0.0

**Please tell us about your environment:**
- **Operating System:**
  OSX 10.11.6
- **Node Version:**
  6.2.0
- **NPM Version:**
  3.8.9
- **JSPM OR Webpack AND Version**
  aurelia-cli 0.16.2
- **Browser:**
  all
- **Language:**
  ESNext

**Current behavior:**

I have a locale key with a contextualised variant. If I set the context somewhere, it remains everywhere I don't set it.

Exemple :

translations.json

```
{
  "foo": "A simple foo",
  "foo_bar": "A foo with a bar"
}
```

app.html

```
<template>
  <pre>&lt;p t="foo"&gt;&lt;/p&gt;
  Should be "A simple foo" and display "A simple foo"</pre>
  <p
    t="foo"></p>

  <hr>
  <pre>&lt;p t="foo" t-params.bind="{ context: 'bar' }"&gt;&lt;/p&gt;
  Should be "A foo with a bar" and display "A foo with a bar"</pre>
  <p
    t="foo"
    t-params.bind="{ context: 'bar' }"></p>

  <hr>
  <pre>&lt;p t="foo"&gt;&lt;/p&gt;
  Should be "A simple foo" but display "A foo with a bar"</pre>
  <p
    t="foo"></p>

  <hr>
  <pre>&lt;p t="foo" t-params.bind="{ context: null }"&gt;&lt;/p&gt;
  Should be "A simple foo" and display "A simple foo"</pre>
  <p
    t="foo"
    t-params.bind="{ context: null }"></p>
</template>

```

**Comment by EisenbergEffect** [comment]
@zewa666 Can you look into this?

**Comment by zewa666** [comment]
Sure, @hadrienl sorry for the delay, could you come up with a small sample that reproduces the issue? It would help me very much to get straight at the action without having to second guess what the current and expected behavior is.

**Comment by hadrienl** [comment]
https://www.dropbox.com/s/788e8mzidjq0zvv/aurelia-i18n-context-bug.zip?dl=0

**Comment by zewa666** [comment]
Ok so the thing is it seems to store any previous `t-params` and reuses them for the next `t` even if there is none provided. If I move your last t-params.bind  with context null to the 3rd, both the 3rd and 4th do work as expected.

Hmm interesting, could be that the last [changes here](https://github.com/aurelia/i18n/blob/master/src/t.js#L96) introduced a side effect.

Thanks for reporting @hadrienl, now I know what to look for

**Comment by zewa666** [comment]
ok its a regression introduced with [this commit](https://github.com/aurelia/i18n/commit/3060e7a647ce6daa0b4de824b358e221c6882e08) in order to cover [issue 116](https://github.com/aurelia/i18n/issues/116), which frankly was also reported by you :)

@Jenselme I've you have time, maybe you can also give this a shot, I'll try to create a patch for it in the meantime

**Comment by zewa666** [comment]
Wow this is new ... one section affects four Bugs ... There is a PR prepared I'll just have to make sure it covers the other bugs as well properly. This will be released soon.

**Comment by Jenselme** [comment]
@zewa666 any progress on this issue? I won't be able to look at it before next week though.

**Comment by zewa666** [comment]
@Jenselme yep, there is a new release pending which should address this.

**Comment by zewa666** [comment]
@Jenselme, @hadrienl you guys had a chance to take another look with the recent version?

**Comment by Jenselme** [comment]
@zewa666 I had not. But I should be able to test this week end.

**Comment by zewa666** [comment]
I did again a test and the original issue is gone for me, as such I'm closing this one. We can reopen it if you guys @Jenselme, @hadrienl still experience issues
