### ISSUE TITLE
Attribute binding causes exception

### ISSUE THREAD

**Issue by oneillci** [aurelia/i18n#146]
**I'm submitting a bug report**

* **Library Version:**
1.1.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
5.3.0

* **NPM Version:**
3.3.12

* **JSPM OR Webpack AND Version**
JSPM 0.16.42

* **Browser:**
Chrome 52 | Firefox 48 | Edge 25 | IE 11

* **Language:**
all

**Current behavior:**
When translating an attribute via t="[title]myKey", the node.au.controller on line 245 (https://github.com/aurelia/i18n/blob/master/src/i18n.js#L245) is undefined resulting in a runtime exception.

The node.au object has a property "t" which appears to be an instance of a Controller. Adding a guard clause for the controller fixes this behaviour as does changing references to node.au.controller to node.au.t.

Happy to submit a pull request for this if I can get guidance as to what it should be. Not sure what unit test I can get to cover this as in the current tests node.au is always undefined and I don't know how to instantiate it in the current tests.

**Expected/desired behavior:**
It should translate without a runtime exception.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

**Comment by zewa666** [comment]
the latest release should fix this now
