### ISSUE TITLE
Detect user language

### ISSUE THREAD

**Issue by mttmccb** [aurelia/i18n#148]
I'm just wondering if this is possible, at the moment when I do the setup I set the default myself, but it would be much better to do this based on the users preference. Based on my initial searches it seems like it's possible find this out by looking in `navigation.languages` and getting the first in this list (some browser inconsistencies here).

In additional to this it would be nice to observe this and change the locale based on browser changes.

Thinking about this in a non-browser setting the way languages are detect may be different so a generic way of doing it would be handy.

Hopefully that makes sense.

**Comment by zewa666** [comment]
One of the reasons I chose i18next as a foundation for Aurelia-I18N is that it comes with a [set of plugins](http://i18next.com/docs/ecosystem/) for different tasks. [One of them](https://github.com/i18next/i18next-browser-languageDetector) exactly being what you're searching for.

**Comment by mttmccb** [comment]
Thanks @zewa666, I'll check it out, clearly my google-fu failed me ;)

**Comment by zewa666** [comment]
@mttmccb it would be a great help if you could post a short summary here, or if you're a blogger guy a link to a post about your findings

**Comment by mttmccb** [comment]
@zewa666 I will blog about it, hopefully this week if it goes smoothly :)

**Comment by mttmccb** [comment]
I hope [Using i18next language detection with Aurelia](https://mttmccb.github.io/using-i18n-language-detection-with-aurelia/) helps someone with this, it was pretty easy to get setup. There are a few other plugins I'll probably be trying out, like [i18next-resource-store-loader](https://github.com/atroo/i18next-resource-store-loader).

**Comment by zewa666** [comment]
Awesome, great post :plus1:
