### ISSUE TITLE
Value not appearing in multi select box when option is added when text is translated

### ISSUE THREAD

**Issue by a-jackson** [aurelia/i18n#156]
**I'm submitting a bug report**
- **Library Version:**
  1.1.2

**Please tell us about your environment:**
- **Operating System:**
  Windows 7
- **Node Version:**
  5.11.1
  
  
- **NPM Version:**
  3.10.2
  
  
- **JSPM OR Webpack AND Version**
  JSPM 0.16.34
  
  
- **Browser:**
  IE 11
- **Language:**
  ESNext

**Current behavior:**
When using a multiple select element, where the options are populated with a `repeat.for`, and the value is translated using a `t` attribute, and there is a value binding on the select element. The added option doesn't display the new value until another new option is added. This only occurs in IE. I've only tested in IE 11 and Chrome 53.

If I use the `t` value converter it does work, however, my translation has html so I'm using `t="[html]${'key'}"` (although issue still occurs without [html]). Also if I remove the `value.bind` on the select element it works (but obviously that binding doesn't)

**Expected/desired behavior:**
The value of the option appears as in Chrome.

[Minimal Demo](https://github.com/aurelia/i18n/files/483018/i18n-select-issue_bb7d0c8e60b729f664f14fb323b8357de91ffdf4.zip)

**Comment by zewa666** [comment]
I think this could be related to this issue: https://github.com/aurelia/i18n/issues/147

**Comment by a-jackson** [comment]
I think it might be related but there is something different because mine works in Chrome, this only affects IE.

**Comment by zewa666** [comment]
To be totally honest, I have absolutely no clue why this happens. What is even crazier, is the fact that inspecting the DOM in IE11 shows that the translated values are supposed to be there. The new textnode with the translation is created and attached as well. So ... I can only think of a relation to the binding process mentioned in the related issue.

**Comment by a-jackson** [comment]
I'll be honest, kind of glad to hear you say that :) I spent a few hours looking at this myself before I submitted it and thought I was going a bit crazy because I could find nothing wrong. Like you say, it's there in the DOM. 

Have you got any suggestions for a workaround? This is our very last outstanding issue and our clients use IE 11 exclusively.

**Comment by zewa666** [comment]
terrible indeed 😆 Instead of crushing our brains, lets hold of and see how the other bug gets fixed, maybe it will give us more insights in this one as well. Thanks for reporting it and sorry for not having a concrete answer yet

**Comment by zewa666** [comment]
I found the bug, yet not sure why it happens. https://github.com/aurelia/i18n/blob/master/src/i18n.js#L159 IE and Edge do strange things if the update process is called within a promise, thus chained to the end of the current task. If you remove the promise.then and instead call _updateValue directly it works. There was a reason for this deferred to make sure we do no translations if the service isn't ready. So I'd like to fix the issue properly instead of just removing the promise. 

Nevertheless I realize you have a ongoing project and this seems to be a blocker, so in the meantime this workaround might do the trick for you to keep your project going.

**Comment by VMBindraban** [comment]
Does the bug you found also apply for #147 ?

**Comment by zewa666** [comment]
I'm pretty sure it is related to it. I've already bugged Jeremy to see how we can fix that properly.

**Comment by zewa666** [comment]
@a-jackson could you give this a try after the recent release. I'm pretty sure this ones now fixed

**Comment by a-jackson** [comment]
Can confirm, it is working on 1.2.0.

**Comment by zewa666** [comment]
Thanks for checking back 👍
