### ISSUE TITLE
Uncaught TypeError: number.replace is not a function

### ISSUE THREAD

**Issue by VMBindraban** [aurelia/i18n#161]
**I'm submitting a bug report**

* **Library Version:**
1.1.1

* **Browser:**
Chrome 52

* **Language:**
ESNext

**Current behavior:**
Throws an error when using `i18n.uf(number)`

https://github.com/aurelia/i18n/blob/master/src/i18n.js#L80

```js
import {inject} from 'aurelia-dependency-injection';
import {I18N} from 'aurelia-i18n';

@inject(I18N)
export class ExampleValueConverter {

  constructor(i18n) {
    this.i18n = i18n;
  }

  toView(value) {
    return this.i18n.uf(value);
  }
}
```

**Expected/desired behavior:**
It should format the number.

**Comment by zewa666** [comment]
Thanks for the bug report, could you give me an example what the value was sent in? I guess the reason is that your Converter first sends in undefined/null or something, not being a number. If so the fix should be pretty obvious by just checking for those examples and returning the same result. If you like you could then also provide a PR in that case

**Comment by VMBindraban** [comment]
The number of values i tired are between 1 and 380. No floating pointers.

**Comment by zewa666** [comment]
ok so could you verify that by adding `console.log(Number.isInteger(value))` in your toView function and see whether only `true`s are logged?

**Comment by VMBindraban** [comment]
The formater gives a number. I will make a PR.

**Comment by VMBindraban** [comment]
I am not really sure anymore what this function does.

When converting it to a string or give it a string it doesn't have the number separators.
When i give it  `100,000.000` as value, it returns as `1`.

**Comment by zewa666** [comment]
so the reason for this function was, if you give it a string, it should unformat it and return a number. So your issue is now solved?

**Comment by VMBindraban** [comment]
It is solved yes. I thought gave it a number and it would format it.

**Comment by zewa666** [comment]
hehe no, thats what nf is supposed to do, unformat does exactly the other way
