### ISSUE TITLE
Sometimes all translations are missing

### ISSUE THREAD

**Issue by Tim-Erwin** [aurelia/i18n#164]
**I'm submitting a bug report**
- **Library Version:**
  1.0.0

**Please tell us about your environment:**
- **Operating System:**
  OSX 10.11, Windows 10
- **Node Version:**
  5.12.0
- **NPM Version:**
  3.8.6
- **JSPM OR Webpack AND Version**
  JSPM 0.16.15
- **Browser:**
  Chrome 53 | Firefox 42 | Firefox 49
- **Language:**
  ESNext

**Current behavior:**
In principle, everything works as expected, the labels in the UI are shown as defined in the language file. I'm using i18next-xhr-backend.

However, sometimes (bad word in error descriptions, sorry) the translations are simply missing. There's no error in the console or anything comparable, the UI works as expected, just the texts are missing. When I then refresh the page, everything is as normal. In an attempt to make the "sometimes" more graspable let me depict my "impression": When I work in other tabs, maybe close the browser, open it again, select the tab again, the application is loaded, but (sometimes) without the translations. So basically I feel this happens mostly when the application has been loaded before, is in some browser cache. Also, since I was never able to deliberately reproduce the problem, it rather happens after a while of not touching the app.

By the way, I'm sadly not the only one with this problem, my clients get that error as well and get really confused by it.

**Expected/desired behavior:**
It would be awesome to always have the texts without the need to refresh the page.

I have no idea how to debug this. I'd be willing to put any helpful code in my copy of i18n and analyze the output when the texts are missing again.

**Comment by zewa666** [comment]
I've never seen this issue so far and it feels somehow that some parts of your app might interfere with the startup process. Is there a chance you create a minimal example which can reproduce the issue?

I'm especially really curious how this can happen since all the things happen asynchronously and as such it should not be possible to come into such an situation.

A bloody hell of dirty fix would be to force updating all translations if you cannot spot the real issue in your app. The easiest thing for that atop of my head would be to trigger a dual setLocale change in your components `attached` hook

**Comment by Tim-Erwin** [comment]
Thanks for your reply. I really have no clue, what a minimal example would look like, because I cannot reliably reproduce the problem. Is there a way to log the translation data that is used? That could at least give a hint whether the problem is in the data or in the processing.

The startup process of the app is pretty straight forward. I'm using basically the defaults plus aurelia-dialog, aurelia-i18n, kenoui-bridge, and aurelia-notification.

**Comment by zewa666** [comment]
There is a new release pending which might could fix this as well. Can I ask you to hold of until this ones out and then do a retest? I'll ping you when its out.

**Comment by Tim-Erwin** [comment]
Ok, will test as soon as possible.

**Comment by zewa666** [comment]
@Tim-Erwin any chance to take a look at it with the recent release?

**Comment by Tim-Erwin** [comment]
Thanks for the ping, will try.

**Comment by Tim-Erwin** [comment]
I deployed the app with the new version. Let's see if it helps...

**Comment by Tim-Erwin** [comment]
No clue what you did there to fix it but the problem hasn't occurred since the update. Thanks.

**Comment by zewa666** [comment]
@Tim-Erwin there were a few things around promise resolution and delayed instantiation of the plugin. I guess one of those changes also fixed your issue. I'm really glad this got resolved. Please do not hesitate to reopen if you experience it again
