### ISSUE TITLE
Custom element camelCase bindable properties bug

### ISSUE THREAD

**Issue by Croissong** [aurelia/i18n#168]
**I'm submitting a bug report**

* **Library Version:**
1.1.2

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
5.11.0

* **NPM Version:**
3.5.2

* **Webpack Version**
webpack 2.1.0-beta.17

* **Browser:**
Chrome

* **Language:**
ESNext

**Current behavior:**

Custom element camelCase bindable properties are not detected when translating via html attributes.

For example `<md-card md-title.bind="'asdsd'" t="[mdTitle]title">`

In MdCard: `@bindable({
    defaultBindingMode: bindingMode.oneTime
  }) mdTitle;`

I believe the [regex](https://github.com/aurelia/i18n/blob/2136fdfe59ad60d0ffcf8062b960a32a3d375085/src/i18n.js#L163) `/\[([a-z\-]*)\]/g` should be case insensitive: `/\[([a-z\-]*)\]/ig`

**Comment by zewa666** [comment]
@Croissong this makes kinda sense ... would you mind creating a PR and tests targeting the [updateValue](https://github.com/aurelia/i18n/blob/2136fdfe59ad60d0ffcf8062b960a32a3d375085/src/i18n.js#L152) method to address your changes?

**Comment by zewa666** [comment]
ok there is a fix in place for that which is scheduled for the next release

**Comment by zewa666** [comment]
@croissong just for completness can you confirm that the recent release fixed you issue?
