### ISSUE TITLE
Override i18next ajax loader to use systemjs loader

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/i18n#17]
i18next uses ajax to fetch the translations. This is causing some path resolving issues. If you add aurelia-i18n to any plugin using this config:
```
instance.setup({
      resGetPath : 'resources/__lng__.json',
      lng : ValidationConfig.defaults.getValue('locale'),
      attributes : [],
      getAsync : true,
      sendMissing : false,
      fallbackLng : 'en-US',
      debug : false
    });
```
and if you then install the plugin, the browser will look for the .json file in localhost:9000/resources/en-US.json instead of localhost:9000/jspm_packages/github/aurelia/validation@0.3.1/resources/en-US.json. i18next allows for an override of the fetching mechanism ([here](https://github.com/i18next/i18next/blob/master/src/i18next.sync.js#L91)). Perhaps aurelia-i18n can override this to use the systemjs loader? I think it would be nice if any aurelia plugin could implement aurelia-i18n.

**Comment by zewa666** [comment]
So using the jspm json plugin should help solving this task I guess. Will have a look at it. Just out of interest, what happens if you add a relative path by prefixing `resGetPath` with `./`?

**Comment by JeroenVinke** [comment]
yes, it would be great of we could use the json plugin. Adding `./` doesn't change anything I'm afraid. 
![image](https://cloud.githubusercontent.com/assets/2189477/9989883/bbedaad0-605c-11e5-86f4-ce334f788af7.png)

**Comment by zewa666** [comment]
ok it seems that System json imports are quite easily done here.
Below find an example how you'd configure the custom loading process. So in your case the validation plugin would need to use that way when referencing i18n.

```
.plugin('aurelia-i18n', (instance) => {
        // adapt options to your needs (see http://i18next.com/pages/doc_init.html)
        instance.setup({
          //resGetPath : 'locale/__lng__/__ns__.json',
          lng : 'de',
          attributes : ['t','i18n'],
          //getAsync : true,
          sendMissing : false,
          fallbackLng : 'en',
          debug : false,
          customLoad: (lng, ns, options, loadComplete) => {
            System.import('../locale/' + lng + '/' + ns + '.json!').then( (data) => {
              loadComplete(null, data)
            });
          }
        });
      });
```

**Comment by JeroenVinke** [comment]
that is awesome, thanks Vildan :+1:  I assume this would also cache already loaded translation files?

**Comment by zewa666** [comment]
it should go through the normal systemjs loading process, which does caching ... so without knowing exactly I'd say yes :)
