### ISSUE TITLE
Issue with i18n and webpack

### ISSUE THREAD

**Issue by mttmccb** [aurelia/i18n#172]
**I'm submitting a bug report**

* **Library Version:**
1.2.1

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12.1

* **Node Version:**
6.8.1

* **NPM Version:**
3.10.8

* **JSPM OR Webpack AND Version**
webpack 2.1.0-beta.25.

* **Browser:**
Chrome 54.0.2840.87

* **Language:**
TypeScript 2.1

**Current behavior:**
Fails with error `instance.i18next.use is not a function`

**Expected/desired behavior:**
Don't fail with any errors. I've cloned the latest skeleton and you can find it in [aurelia skeleton with i18n issue](https://github.com/mttmccb/aurelia-skeleton-with-i18n-issue)

I haven't been able to narrow down which library has caused this.

**Comment by Tarpsvo** [comment]
It's super weird. I tried different versions of `aurelia-i18n` and `Webpack`, but can't get it to work even with the versions that previously worked.

**Comment by mttmccb** [comment]
I've also updated skeleton-typescript (the non-webpack version) and that works ok.

**Comment by zewa666** [comment]
Ok I will have a look at it later today.

**Comment by Tarpsvo** [comment]
Could be `i18n` (or some other dependency update) that breaks it. I can't get my project to work with ANY `aurelia-i18n` version anymore.

**Comment by Tarpsvo** [comment]
Fixed it by fixing the `i18next` version to `3.4.4`.

**Comment by zewa666** [comment]
Its actually a 3rd Party issue https://github.com/i18next/i18next/issues/836. So @Tarpsvo your solution is the way to go until this external issue gets fixed

**Comment by Tarpsvo** [comment]
Seems like an appropriate time to ask this question: why don't Aurelia modules like this use fixed versioning on their dependencies?

**Comment by zewa666** [comment]
Could make sense, the problem with this though is that it becomes harder to find out about certain issues. We also do build upon i18next in order to benefit from their experience and progress. Looking the version down as such would also reduce this benefit.

**Comment by jamuhl** [comment]
hi there. i'm maintain i18next...the issue was introduced with adding the `module` entry point for webpack 2 which leads to a same build as used for rollup (transpiled but keeping import/export to enable treeshaking).

so right now we still investigate on what's the way to go: basically using `import i18next from 'i18next';` works as long you do not run babel over it again.

not yet sure what the right path to go is. Discussion is welcome here: https://github.com/i18next/i18next/issues/836

**Comment by jamuhl** [comment]
for the sake of getting this semver compatible:

3.5.2 -> removed the module entry point and will work as used
4.0.0 -> adds the entry point module for webpack2

4.0.0 works with webpack2-beta under following conditions:

you only use import import i18next from 'i18next';
you do not run babel over that files

**Comment by zewa666** [comment]
welcome @jamuhl, nice to have you visiting us :)
Thanks for your explanation and proper SemVer handling. This definitely fixes our issue.
As going forward with the major upgrade I need to take a closer look any way, but so far its enough to close this issue.

Thanks to all for raising and helping to get this done
