### ISSUE TITLE
nf function return type in I18N class aurelia-i18n.d.ts

### ISSUE THREAD

**Issue by EduwHS** [aurelia/i18n#176]
I checked the implementation of this function and it's returning a NumberFormat, shouldn't the d.ts interface return : any? 
It's currently returning a String
aurelia-i18n.d.ts line 46
nf(options?: any, locales?: any): string;

**Comment by zewa666** [comment]
@EduwHS thanks for the info. Would you like to create a PR for that? By doing so maybe the same applies to the DateTimeFormat?
