### ISSUE TITLE
dot notation translations only appear to work if using the `i18n` at least once

### ISSUE THREAD

**Issue by PWKad** [aurelia/i18n#180]
If you have -

```markup
<template>
  <input placeholder="Username" t="[placeholder]login.username" />
  <input placeholder="Password" t="[placeholder]login.password" />
  <button t="login.login">${Login}</button>
</template>
```

Everything initially shows the `login.login` instead of the translation.

When switching one of the `t=` to `i18n=` they all start working.

**Comment by PWKad** [comment]
This could absolutely be due to something else the more I see it, seems like with browserSync on reloads sometimes the translations aren't loaded or something.  Still investigating, will provide more info if I can figure it out, else I will close it.

**Comment by zewa666** [comment]
thanks @PWKad sounds like a weird race-condition

**Comment by PWKad** [comment]
Closing for now as I was unable to find a cause, it isn't easily reproducible as browserSync intermittently seems to refresh the page without translation applied and showing the `name.translation` string itself in the html.  If I can repro will re-open.
