### ISSUE TITLE
TypeScript - typings/modules/aurelia-i18n/index.d.ts(4,8): error TS1192: Module ''i18next'' has no default export.

### ISSUE THREAD

**Issue by PWKad** [aurelia/i18n#181]
When using the aurelia-i18n type definitions the following error is thrown - 

`typings/modules/aurelia-i18n/index.d.ts(4,8): error TS1192: Module ''i18next'' has no default export.`

Because the top of the type definition - 

```
declare module 'aurelia-i18n' {
import i18next from 'i18next';
//...
```
should actually be 

```
declare module 'aurelia-i18n' {
import * as i18next from 'i18next';
//...
```

**Comment by zewa666** [comment]
this issue came up several times here and is a problem due to the way how we need to import the original source of i18next. Take a look here https://github.com/aurelia/i18n/pull/171 and the referenced issue

I'm happy for any inputs if you see a better solution.

**Comment by PWKad** [comment]
Got it my bust for a dupe.
