### ISSUE TITLE
aurelia-i18n - typescript - module not found

### ISSUE THREAD

**Issue by jcarruo** [aurelia/i18n#183]
**I'm submitting a bug report**

* **Library Version:**
1.2.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
4.6.1

* **NPM Version:**
3.10.8

* **JSPM OR Webpack AND Version**
JSPM 0.16.48

* **Browser:**
Chrome  54.0.2840.99 m

* **Language:**
TypeScript 2.1.4

**Current behavior:**

I have:

- Installed aurelia-i18n via jspm

- Installed typescript definitions as per https://github.com/aurelia/i18n/blob/master/doc/article/en-US/i18n-with-aurelia.md

- Copied the aurelia.d.ts definition file into my typings folder and updatd index.d.ts (working from typescript navigation skeleton).

The following line produces "[ts] cannot find module 'aurelia-i18n'".

import {I18N} from 'aurelia-i18n';

This behaviour was not present in v1.1.2.

All current imports for standard aurelia-frameworks are working with their respective typescript definitions.

**Expected/desired behavior:**

* **What is the expected behavior?**
Module should be resolved correctly.

* **What is the motivation / use case for changing the behavior?**

**Comment by EisenbergEffect** [comment]
Ping @zewa666

**Comment by zewa666** [comment]
@jcarruo I can't really replicate the issue.

Meantime it's even easier to get rolling and I'll update the README.
In short what I did was:

1. Download TS Skeleton
2. NPM / JSPM Install
3. jspm install aurelia-i18next
4. jspm install npm:i18next-xhr-backend
5. typings install dt~i18next --save --global
    typings install dt~i18next-xhr-backend --save --global
    typings install github:aurelia-i18next (this will install the i18n plugins d.ts)
6. add `"allowSyntheticDefaultImports": true,` so you can keep
    `import {I18N}  from 'aurelia-i18n';` otherwise you need to
    `import * as I18N from 'aurelia-i18n';`

Can you retry and see if that helps?

**Comment by jcarruo** [comment]
`"allowSyntheticDefaultImports": true` was the key.  Thanks!!
