### ISSUE TITLE
i18n.updateTranslation() doesn't work with i18next.loadNamespaces()

### ISSUE THREAD

**Issue by mreiche** [aurelia/i18n#185]
The following code
```
import {I18N} from 'aurelia-i18n';

@inject(I18N,Element)
export class MyApp {
	constructor( i18n, element) {
		this.i18n = i18n;
		this.element = element;
		this.i18n.i18next.loadNamespaces(['backend','navigation','filemanager'],(err,t)=>{
			console.log('update translations');
			this.i18n.updateTranslations(this.element);
		});
	}
	attached() {
		this.i18n.updateTranslations(this.element);
	}
}
```
Loads the namespaces and updates i18n, but doesn't refresh the view.

**Comment by zewa666** [comment]
can you check whether this is a timing issue? E.g. just delay the attached update call.
Otherwise I'd like to ask you to provide a sample so I can take a look at your issue without having to recreate the whole environment

**Comment by mreiche** [comment]
It seems not to be a timing issue. This doesn't work either:
```
attached() {
	const self = this;
	window.setTimeout(function() {
		console.log('update translations delayed');
		self.i18n.updateTranslations(this.element);
	},5000);
}
```

> Otherwise I'd like to ask you to provide a sample so I can take a look at your issue without having to recreate the whole environment and issue specific setups

This may take some time. I try to get a Gist running asap.

**Comment by mreiche** [comment]
Meanwhile I got a hint. It works when I update the language:
```
<button click.delegate="changeLanguage()">Change language</button>
```
```
changeLanguage() {
	this.i18n.setLocale('en').then(() => this.i18n.updateTranslations(this.element));
}
```

**Comment by mreiche** [comment]
Dammit.  It also works in my example gist: https://gist.run/?id=c867eee507b9cece7809eb95ccb6bea7
