### ISSUE TITLE
Binding to data attributes does not work as expected

### ISSUE THREAD

**Issue by Tarpsvo** [aurelia/i18n#187]
**I'm submitting a bug report/feature request**
* **Library Version:**
1.2.3

Line in question:
https://github.com/aurelia/i18n/blob/master/src/i18n.js#L185

This line basically converts the attribute specified into camelcase (removing dashes), so if I bind to `data-content` for example, I will get the `dataContent` attribute on the element instead.

So basically:
`i18n="[data-content]something"`
turns into
`datacontent="something"`

This is not an expected result for me, for it disallows translating strings into to `data-` attributes. I scanned through the code and didn't really see a reason for the camelcase conversion.

I fixed it on my local by just removing the camelcase conversion part. Any ideas on fixing it in the library in general?

**Comment by Tarpsvo** [comment]
Just noticed this.

https://github.com/aurelia/i18n/commit/e70372c

Oh, well.

**Comment by zewa666** [comment]
@Tarpsvo hm don't know how that one slipped through. Thanks for the hint, fixed and scheduled for release

**Comment by zewa666** [comment]
@Tarpsvo can you check this again, the latest release should have fixed it

**Comment by Tarpsvo** [comment]
Cool beans, it works as expected. Good job and thanks a ton! :)

**Comment by zewa666** [comment]
@Tarpsvo thanks for reporting the issue
