### ISSUE TITLE
Intl.js polyfill

### ISSUE THREAD

**Issue by Mordred** [aurelia/i18n#19]
I'm getting error `XHR error (404 Not Found) loading http://example.com/Intl.js` on Safari. Problem is that you are loading `Intl` here https://github.com/aurelia/i18n/blob/master/src/i18n.js#L16 but dependency is called `Intl.js` inside `package.json` https://github.com/aurelia/i18n/blob/master/package.json#L29 so it should be also loaded as `Intl.js`

**Comment by zewa666** [comment]
Hmm thats strange, I think this used to work earlier. Whyever the naming is wrong, even with the proper one it still fails to load the file as it seems to request it from the perspective of the skeleton app. Need to investigate this a bit more.

**Comment by Mordred** [comment]
Any news?

**Comment by zewa666** [comment]
was able to reproduce the issue myself. its on the list and will get to it asap. The necessary internal API changes have been made in the meantime so the fix should hopefully be easy

**Comment by zewa666** [comment]
@Mordred the recent release should fix that, please try it out

**Comment by Mordred** [comment]
Good job, it works.
