### ISSUE TITLE
Document: session explaining t-params is missing

### ISSUE THREAD

**Issue by Holi0317** [aurelia/i18n#190]
**I'm submitting a bug report**

* **Library Version:**
1.3.0

**Please tell us about your environment:**
* **Operating System:**
Linux (Arch Linux)

* **Node Version:**
7.3.0

* **NPM Version:**
4.0.5

* **JSPM OR Webpack AND Version**
(Not available)

* **Browser:**
all

* **Language:**
all

**Current behavior:**
On line 594 of [i18n document](https://github.com/aurelia/i18n/blob/master/doc/article/en-US/i18n-with-aurelia.md), the link to `in the next section` redirects to a 404 page.

**Expected/desired behavior:**

* **What is the expected behavior?**
The link should bring to an existing page explaining t-params structure.

* **What is the motivation / use case for changing the behavior?**
For better documentation?

**Comment by zewa666** [comment]
ok thanks for the hint, I've updated the docs, will be pushed with the next Hubs release
