### ISSUE TITLE
i18next typings incompatibility issue

### ISSUE THREAD

**Issue by llicht** [aurelia/i18n#191]
**I'm submitting a bug report**

* **Library Version:**
1.3.0

**Please tell us about your environment:**

* **Node Version:**
6.9.1

* **NPM Version:**
3.10.9

* **Language:**
TypeScript 2.1

**Current behavior:**
aurelia-i18n.d.ts contains the line "import i18next from 'i18next';".
However, the official typescript definitions for i18next (@types/i18next) do not default export anything from the module, resulting in a build error:
<..>/node_modules/aurelia-i18n/dist/aurelia-i18n.d.ts(1,8): error TS1192: Module '"<..>/node_modules/@types/i18next/index"' has no default export.
Please also note that this import isn't actually used in aurelia-i18n.d.ts itself (even though it probably could be used, e.g. using i18next's Options instead of any in I18N.setup).

**Expected/desired behavior:**

Either aurelia-i18n.d.ts wouldn't import i18next at all (if it doesn't use it), or it would import it in a way that's compatible with the official typing definitions. (e.g. import * as i18next from 'i18next')

* **What is the motivation / use case for changing the behavior?**
Current behaviour causes a typescript build error.

Thanks!

**Comment by zewa666** [comment]
This issue is related to how TypeScript handles synthetic default exports. Please refer to this issue. https://github.com/aurelia/i18n/issues/186
