### ISSUE TITLE
Human readable durations.

### ISSUE THREAD

**Issue by bas080** [aurelia/i18n#194]
**I'm submitting a feature request**

**Library Version:**
1.3.0

**Current behavior:**
There is currently no way to translate a duration to a human readable string. I understand the issue as it requires a way of defining durations. The simplest I can think of is by providing two dates and getting a human readable string. e.g.

**Expected/desired behavior:**
```js
  this.i18n.dd(event.startDate, event.endDate) // => '2 hour and 20 seconds'
```

The `dd` stands for `Date Duration`

**What is the motivation / use case for changing the behavior?**
It's a useful feature and in my opinion it makes sense to have it here. It might be really easy to implement too. It's similar to the `relative time` string, but then without the `ago`.

**Comment by zewa666** [comment]
A good idea for an enhancement, allthough I'm not sure if this exceeds the plugins point. Calculating durations is not as straight forward as thought, think about leap years and varying formats (calendar, business e.g bank etc.). Thats just one part, after that creating a human readable format is another thing.

Should 3,660sec be 61 minutes, or 1 hour and 1 minute or 1 hour and 60 seconds? You see without the proper context and granularity definition it can be hard to reason about that.

A third point are the concatenators. If we have 2 hours 20 min and 2 sec do you return
*2 hours and 20 minutes and 2 seconds* or do you use a comma as concatenator?

It sounds similar to relative time, with the exception though that RT has a fixed context. Its the time thats passed in human words, relative to now. A duration itself on the other hand is a function of start and end. So with two inputs, the problems/questions are doubled as well :)

I hope you see what my point is. I really do like the idea, I'm just not sure whether its the proper fit for this plugin. Essentially aurelia-i18n cares about internationalization, wheras your proposed feature cares more about date/duration arithemtics, which is something libraries like Moment.JS are great at.

What do you think?

**Comment by peterver** [comment]
@zewa666 Just giving my 50cents on this done, but this doesn't sound like a job for i18n as it would most likely increase the size of the repo by a lot ( taking timezones etc into account ).

What would help tremendously is if someone could setup an example / article with custom value converters for use cases like this ( better to teach a man how to fish than give him a fish i guess ).

**Comment by zewa666** [comment]
@peterver we'd welcome such an article and I'm sure @EisenbergEffect would be ok to even post it on the main aurelia-blog. So whoever volunteers to do so, make sure to ping me in gitter and I'll help out where I can.

@bas080 I'd still be interested in your answer to this, since you opened the issue. Maybe you have some different use cases we haven't thought of yet.

**Comment by bas080** [comment]
@zewa666, I can see that this feature surpasses the responsibility of aurelia-i18n.
