### ISSUE TITLE
t attribute with slots produces error

### ISSUE THREAD

**Issue by RWOverdijk** [aurelia/i18n#197]
**I'm submitting a bug report**

* **Library Version:**
1.3.0

* **Operating System:**
OSX 10.x

* **Browser:**
Chrome 56

* **Language:**
ESNext

Combining the `t` attribute with slots causes an error to occur.

```html
<template>
  <label t.bind="value" class="control-label ${classes}">
    <slot name="before"></slot>
    ${value}
    <slot name="after"></slot>
  </label>
</template>
```

* **What is the expected behavior?**
I expect it to replace the content with a translation, if value is of type string (`null` gets skipped already).

* **What is the motivation / use case for changing the behavior?**
I want to allow the following behaviors for my custom element:

1. Supply a value through a value attribute. This gets used and translated.
2. Supply a before slot to put something before the value.
3. Supply an after slot to put something after the value.

Usage example:

```html
<form-label value="Hello">
  <strong slot="after">World</strong>
</form-label>
```

Which now gives me:

```
ERROR [app-router] TypeError: Cannot read property 'insertBefore' of null
    at ShadowSlot.addNode (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.2.0/aurelia-templating.js:951:15)
    at Function.distributeNodes (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.2.0/aurelia-templating.js:1198:21)
    at Function.distributeView (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.2.0/aurelia-templating.js:1161:17)
// Cutting short trace for the issue.
```

**Update:**
I do realize that a value would overwrite my slots. It's weird, but a thing I want to do. It's how we allow for custom components with optional i18n (soft dependency).

**Comment by zewa666** [comment]
@RWOverdijk hi, can you come up with a small example that replicates the issue?

**Comment by RWOverdijk** [comment]
Sure. Easy:

```html
<label t.bind="value">
  <slot name="foo"></slot>
</label>
```

```js
export class MyViewModel {
  value = 'hello world';
}
```

**Comment by RWOverdijk** [comment]
@zewa666 

Sure. Easy:

```html
<label t.bind="value">
  <slot name="foo"></slot>
</label>
```

```js
export class MyViewModel {
  value = 'hello world';
}
```

**Comment by stsje** [comment]
Wouldn't you use the translation value-converter instead of the `t` attribute in this case?
```
<template>
  <label class="control-label ${classes}">
    <slot name="before"></slot>
    ${value | t}
    <slot name="after"></slot>
  </label>
</template>
```

**Comment by bas080** [comment]
@stsje, Using the t customAttribute allows you to implement translation in plugins without needing a hard dependency on translation. custom attributes are ignored while value converters that are not defined are not.

**Comment by stsje** [comment]
@bas080 I see. Maybe the plugin authors should provide their own dummy implementation if the plugin isn't loaded? Abstract away the i18n dependency.

When the plugin is loaded, maybe it could check to see if the `t` binding behavior, custom attribute, or value-converter exist?
I think Aurelia's `ViewResources` can be used for it
```
export function configure(config) {
  let viewResources = config.container.get(ViewResources);
  let hasI18nPlugin = 
    viewResources.getAttribute('t') !== null &&
    viewResources.getBindingBehavior('t') !== null &&
    viewResources.getValueConverter('t') !== null;

  if (!hasI18nPlugin) {
    config.globalResources(['./dummy-t']);
  }
}
```
I'm not sure if there's a better way of checking if the i18n plugin is being used or not. Also it requires the i18n plugin to be configured first.

**Comment by RWOverdijk** [comment]
@stsje Using the attribute is an awesome way, as it's easy to supply a fallback. I solved this issue using a span, but I think it's still a bug.

**Comment by zewa666** [comment]
@RWOverdijk I can't replicate any issue with your mentioned example. The thing is that the custom attribute from label, will simply wipe all the contents of the label as such I can't see how this is going to create an issue. This is also the main use-case of the attribute based translation. Also providing null, means that your data isn't loaded or set, as such it won't touch the element and simply keep whats in there.

I'm not sure I understand your use case

**Comment by RWOverdijk** [comment]
@zewa666 That works fine for me. It just doesn't work as soon as I add slots. Perhaps it's something in combination with something else in my application, if you can't reproduce it.

**Comment by zewa666** [comment]
Oki doki, if you manage to find the root cause and its still related to i18n lets reopen this one again.

**Comment by mar9000** [comment]
I think I encountered a bug/feature request related to this issue.

As you can see in this gist, I set up using ``aurelia-materiali-bridge``, https://gist.run/?id=c7e1c50ba6073c7c27c0fd2bb277e002 the last checkbox does not show correctly, see also the app.html comments.

This is due to the actual implementation of checkbox, see https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/src/checkbox/checkbox.html , in aurelia-materialize-bridge, that is using slot.
Slot are working fine for non translated checkboxes, but for translated one ``i18n.updateValue()``, if ``attr == 'text' ``, runs through this code:
```js
node._newChild = newChild;
while (node.firstChild) {
          node.removeChild(node.firstChild);
}
```
removing the internal representation of the custom element, in this case our ``md-checkbox``.

As stated into the aurelia-i18n documentation the default behavior is to replace the ``textContent`` of the element, so one can still consider this is not a bug. However I think the behavior break the standard projection using slots used by aurelia. Moreover a developer should be aware of the internal implementation of the components he or she is using.

Also for me the workaround is to wrap the content into a ``span`` element, as you can see in the gist indicated above.

**Comment by zewa666** [comment]
@mar9000 what would really help is maybe to expand the docs section and explain in short like you did whats happening and how you can work around the issue, namely the `span` including a small code example for the markup. If you would be up to creating a PR for that I think that could help others stumbling across the same problem

**Comment by mar9000** [comment]
@zewa666 I can do it.
Can I ask why you don't think this is a bug or at least a FR? Don't you think it's confusing that aurelia maps content into slot but aurelia-i18n does not? Just asking I don't know if it's possible to do it.

**Comment by zewa666** [comment]
well its no bug, thats what it was reported like. If you feel this makes a good candidate for a general use case, please lets open up a new feature request and address forward discussion over there, maybe with a link to this issue.
