### ISSUE TITLE
Update to I18Next version 9.0.0

### ISSUE THREAD

**Issue by zewa666** [aurelia/i18n#199]
Besides keeping up to date with the next version of i18next, this will also likely solve a often stated issue with TS not understsanding syntheticDefaultExports per default.

See PRs issues:
https://github.com/aurelia/i18n/pull/198
https://github.com/aurelia/i18n/pull/196
https://github.com/aurelia/i18n/pull/171
https://github.com/aurelia/i18n/issues/191
https://github.com/aurelia/i18n/issues/183
https://github.com/aurelia/i18n/issues/182

**Comment by dweggemans** [comment]
I'd make that 9.0.0 which was released 13 days ago. Any ETA on this? There are some issues fixed that I ran into so I'd love to get the updated package.

**Comment by zewa666** [comment]
Thats the next thing I'm going to target. Thanks for pointing out the latest release. I'm stuffed with work currently but this is definitely the next thing I'll do once I have a few spare moments

**Comment by zewa666** [comment]
The update is pushed to master, as soon as we have a new release all should work.
Make sure to not use any v1 options for i18next anymore as support for those depcricated styles has been dropped with 9.0.0
