### ISSUE TITLE
loading viewmodel specific translations

### ISSUE THREAD

**Issue by stuartbloom** [aurelia/i18n#201]
Hi there, I know this is a question and not an issue.

Is it possible, to load a global translations file in the setup of the plugin, but then to load a specific one for each viewmodel.

Thanks

**Comment by zewa666** [comment]
Hi there, yes you can add resources at runtime whenever required. The global thingy is done as described in all the examples and for dynamic additions just get hold of the i18next reference via the i18n service and call the [addResource/s/Bundle](http://i18next.com/docs/api/#add-resource) functions according to your needs.

Typically whenever you need to do any more complex stuff, chances are pretty high that i18next (the thing wrapped by this plugin) offers something out of the box. So consulting their docs and or googling for said information will help you get your work done.

Besides that our official gitter channel might be a better resource to get quicker answers to any upcoming questions. The github issues are primarily used for bug tracking and feature requests.
