### ISSUE TITLE
issue with building.

### ISSUE THREAD

**Issue by stuartbloom** [aurelia/i18n#204]
Hi

I am able to perform an au run and the application works perfectly.

When i perform a au build --env prod, the build runs, I then copy the files to my IIS folder, but when i browse to it I am getting the following error:

![image](https://cloud.githubusercontent.com/assets/7871566/24404155/ff345eaa-13b7-11e7-97ec-6ee9f0d2e30c.png)

I assume there is something missing in my aurelia.json file, but I am not sure what.

Can someone point me in the right direction?

Thanks in advance

**Comment by zewa666** [comment]
hi, make sure you've the backend addon to the aurelia.json file as described here http://aurelia.io/hub.html#/doc/article/aurelia/i18n/latest/i18n-with-aurelia/2

**Comment by stuartbloom** [comment]
Thanks for your response; but I do; file attached.
[aurelia.zip](https://github.com/aurelia/i18n/files/876230/aurelia.zip)

**Comment by stuartbloom** [comment]
I have build a new application from the start and it works fine.

I must have something wrong with my current app.  I will go back and rebuild it.

Thanks for your time :)
