### ISSUE TITLE
i18n attribute not working in globally registered custom elements

### ISSUE THREAD

**Issue by ry8806** [aurelia/i18n#206]
**I'm submitting a bug report**

* **Library Version:**
1.4.0

* **Browser:**
all

* **Language:**
all 

**Current behavior:**
Using attribute [i18n] inside a globally registered custom element, does not work
"Locally" (using <require>) registered custom elements with [i18n] inside work

**Expected/desired behavior:**
i18m (and all registered attributes) work in globally registered custom elements

I couldn't figure out how to add aurelia-i18n to the gist.run examples, so have made a repo replicating the bug here: https://github.com/ry8806/Aurelia-i18n-bug

**Comment by zewa666** [comment]
Thats related to https://github.com/aurelia/i18n/issues/192. 
Please see the instructions provided there for how to make it work.

**Comment by zewa666** [comment]
Actually I totally forgot about adding that. I would be very glad if you could do so @ry8806. To do that just edit the [https://github.com/aurelia/i18n/blob/master/doc/article/en-US/i18n-with-aurelia.md](i18n-with-aurelia.md) file in the repo and a create a PR. Thanks for the offer.

I'll close this issue for now, but when creating the PR please make sure to reference this issue.
