### ISSUE TITLE
Built-in attributes are missing when using configureAliases with reflect-metadata 

### ISSUE THREAD

**Issue by timfish** [aurelia/i18n#209]
I've opened a new issue to cover my findings [at the end of this issue](https://github.com/aurelia/i18n/issues/192). 

When using the new `configureAliases` methods with `reflect-metadata`, aurelia is missing all the built in attributes from `aurelia-templating-resources` and so any basic app will not load.

This can be reproduced by:
- Taking the basic Typescript skeleton
- Add i18n and use the new `configureAliases` methods
- `jspm install reflect-metadata`
- Add `import 'reflect-metadata';` to the top of `main.ts`

~~This repo also reproduces the issue: https://github.com/timfish/aurelia-i18n-issue192~~

**Comment by EisenbergEffect** [comment]
@zewa666 Can you look into this?

**Comment by zewa666** [comment]
@EisenbergEffect sure, @timfish I can't start with the repo mentioned since its lacking a `input-placeholder` whatever. Can you try to bring the repo to a buildable state?

**Comment by timfish** [comment]
Sorry, my bad. Check this one out: https://github.com/timfish/aurelia-i18n-issue-209

[First commit](https://github.com/timfish/aurelia-i18n-issue-209/commit/dcf5e6825c6f2e5473f37c9f3cfcf5aefa344304) - Initial add skeleton
[Second commit](https://github.com/timfish/aurelia-i18n-issue-209/commit/e6915467217d18affae583eade8dd404c7d10b5a) - Basic i18n working with `configureAliases`
[Third commit](https://github.com/timfish/aurelia-i18n-issue-209/commit/f1a6658a462c628fb21d007a0b10d4dc684cd011) - Simply added `reflect-metadata`

**Comment by zewa666** [comment]
@EisenbergEffect wow that seems to be something really strange. Its not related to the aliases at all but if I do the following:

```
import 'bootstrap';
import {Aurelia} from 'aurelia-framework';
import { I18N, TCustomAttribute, TParamsCustomAttribute } from 'aurelia-i18n';
import * as Backend from 'i18next-xhr-backend';
import 'reflect-metadata';

export function configure(aurelia: Aurelia) {
  console.log(TCustomAttribute)
}
```

It's already enough to raise the issue.
Could it be that the bootstrapper/framework is not done yet and thus creating the issue?

**Comment by EisenbergEffect** [comment]
Possibly, reflect-metadata is added too late....and so you get one method of storing metadata being replaced by another and they aren't reading the metadata from the same spot. Just a guess...

**Comment by zewa666** [comment]
@EisenbergEffect you're right. @timfish in your example if I remove the import of reflect-metadata in `main.ts` and change the index.html to look like:

```
<script src="jspm_packages/system.js"></script>
    <script src="config.js"></script>
    <script src="jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js"></script>
    <script>
      System.import('reflect-metadata').then( () => {
        System.import('aurelia-bootstrapper');  
      });
    </script>
```

everything works properly

**Comment by timfish** [comment]
@zewa666 Thanks for tracking this down. 

Its probably just enough to document this somewhere?

**Comment by zewa666** [comment]
I mean it would be nice if we could track down the reason why it doesn't work, but I suspect this will quite hard so for the begin a update for the docs would be the way to go.
Could you create a PR for that @timfish?

**Comment by timfish** [comment]
Before `#typescript-support` I could add a reflect-metadata heading with some details, the above code and link to this issue?

**Comment by zewa666** [comment]
yeah that sounds good

**Comment by timfish** [comment]
https://github.com/aurelia/i18n/pull/210

Is this an issue with Webpack/CLI too?

**Comment by zewa666** [comment]
hm I guess so

**Comment by zewa666** [comment]
I'm closing this for now since it is documented. If we experience further issues we can reopen this one
