### ISSUE TITLE
t attribute colon in translation

### ISSUE THREAD

**Issue by RWOverdijk** [aurelia/i18n#211]
`t="00:00"` produces output: `00`. There's no key in my locale files with value "00:00" yet. Does the colon have special meaning?

`<span t="asa00:0asas0"></span>` produces `Hello! 0asas0` etc.

**Comment by RWOverdijk** [comment]
Just heard this is "namespacing". Can this be disabled?

**Comment by zewa666** [comment]
Yes the colon is used by default as the `nsSeparator` in i18next. Take a look at their [options documentation](http://i18next.com/docs/options/). The idea is that you can split your translations among multiple translations files/categories and thus conceptually keep together whats defining a context.

To allow colons to be used as part of your key you'd have to define a different nsSeparator in the plugin initialization and that should work. Separators can be multiple characters as well.
