### ISSUE TITLE
localesProcessor doesn't work

### ISSUE THREAD

**Issue by bmarotta** [aurelia/i18n#212]
**I'm submitting a bug report**

* **Library Version:**
1.5.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.8.0

* **NPM Version:**
3.10.10

* **Browser:**
all

* **Language:**
TypeScript 1.9.0

**Current behavior:**
First of all, the documentation is outdated. To get it working with aurelia-cli one has also to change the build.ts file and the changes on the run.ts are also not 100% correct.
After the build the app-bundle.js is mal-formed. Example follows below:

```
(...)
{
  "Display numbers": "Display numbers",
  "Easy": "Easy",
  "Hard": "Hard",
  "Medium": "Medium",
  "Open Image": "Open Image",
  "Solve": "Solve",
  "Start": "Start",
  "Stop": "Stop"
}
{
  "Display numbers": "Nummern zeigen",
  "Easy": "Einfach",
  "Hard": "Schwierig",
  "Medium": "Mittle",
  "Open Image": "Bild auswählen",
  "Solve": "Lösen",
  "Start": "Starten",
  "Stop": "Stoppen"
}
{
  "Display numbers": "Mostrar números",
  "Easy": "Fácil",
  "Hard": "Difícil",
  "Medium": "Médio",
  "Open Image": "Escolher imagem",
  "Solve": "Solucionar",
  "Start": "Iniciar",
  "Stop": "Parar"
}

define("locales/en/translation", [],function(){});

define("locales/en/translation", [],function(){});


define("locales/de/translation", [],function(){});

define("locales/de/translation", [],function(){});


define("locales/pt/translation", [],function(){});

define("locales/pt/translation", [],function(){});
(...)
```

**Expected/desired behavior:**
The app-bundle.js should be a valid javascript file

**Comment by bmarotta** [comment]
OK. I found the solution. The json files must also be added to the "text" plugin section of the aurelia.json as below. Please update the documentation.
```

"plugins": [
        {
          "name": "text",
          "extensions": [
            ".html",
            ".css",
            ".json"
          ],
          "stub": true
        }
      ]
```

**Comment by zewa666** [comment]
@bmarotta we'd happily accept a PR for that. If you wanna give it a try, just [edit this file](https://github.com/aurelia/i18n/blob/master/doc/article/en-US/i18n-with-aurelia.md) and add your changes.

**Comment by bryceg** [comment]
@bmarotta Thanks for this, the missing steps on the build.ts file that are not documented was what my problem ended up being, as the translation files were not being bundled in...

**Comment by zewa666** [comment]
@bmarotta and @bryceg I've added an additional note with the recent docs update, although tbh the part you mentioned was already present before https://github.com/aurelia/i18n/blob/master/doc/article/en-US/i18n-with-aurelia.md#bundle-translation-files
