### ISSUE TITLE
IE11 error: Object doesn't support property or method 'isInteger'

### ISSUE THREAD

**Issue by enrico-padovani** [aurelia/i18n#213]
**I'm submitting a bug report**

* **Library Version:**
1.5.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.10.0

* **NPM Version:**
4.5.0

* **JSPM OR Webpack AND Version**
2.1.0-beta.22

* **Browser:**
IE 11

* **Language:**
TypeScript 2.2.2

**Current behavior:**
When trying to format a date the error occours. 

`${myDate | df: { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }: language}`

**Expected/desired behavior:**
Since IE11 is supported, I'd suggest to change Number.isInteger() in something else or to include a polyfill like this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger

**Comment by zewa666** [comment]
@enrico-padovani thanks for checking that out. Good catch, this should be fixed with the next release. Meanwhile as you proposed just add the polyfill yourself to your app.

**Comment by enrico-padovani** [comment]
I see this was addressed by 1.6.0 release. Tested and worked.

**Comment by zewa666** [comment]
@enrico-padovani thanks for the feedback
