### ISSUE TITLE
Phantomjs undefined is not an object (evaluating 'target.__useDefault')

### ISSUE THREAD

**Issue by salihbaki** [aurelia/i18n#216]
There is no error when running on browsers , but i have prerender service running and that service uses phantomjs. 

When i remove .plugin('aurelia-i18n', (instance) => {  ...
phantomjs does not give any error and perfectly prerenders project.

I tried promise polyfills (bluebird). 

But the error still there .

Error is shown at vendor-bundle.js

function ensureOriginOnExports(executed, name) {
    var target = executed;
    var key = void 0;
    var exportedValue = void 0;

    if (target.__useDefault) {
      target = target['default'];
    }

and ensureOriginOnExports used here : 

DefaultLoader.prototype.loadModule = function (id) {
      var _this2 = this;

      var existing = this.moduleRegistry[id];
      if (existing !== undefined) {
        return Promise.resolve(existing);
      }

      return new Promise(function (resolve, reject) {
        require([id], function (m) {
          _this2.moduleRegistry[id] = m;
          resolve(ensureOriginOnExports(m, id));
        }, reject);
      });
    };

**Comment by zewa666** [comment]
First of all it is always helpful if you create the issue using our issue template. As of now we'd have to second guess bundler/loader you've used, I guess its an aurelia cli app right? Which OS?

With the provided error information I can't really figure out whats going on. Have you tried adding additional polyfills to your setup to ensure that its not due to lack of supported features. you could try to either load es6-shim or babel-polyfill or even core-js.

Last but not least if you could setup an example which is reproducible, that would help.

**Comment by salihbaki** [comment]
I used angular-cli with typescript , OS is linux-ubuntu. 
I also tried bluebird , promise polyfill , babel-polyfill ,

The problem is spesific when i use aurelia-i18n plugin ,Phantomjs gives error : 

TypeError: undefined is not an object (evaluating 'target.__useDefault')

  http://www.chooseclick.com:8082/scripts/vendor-bundle.js:13659 in ensureOriginOnExports
  http://www.chooseclick.com:8082/scripts/vendor-bundle.js:13767
  http://www.chooseclick.com:8082/scripts/vendor-bundle.js:5480 in execCb
  http://www.chooseclick.com:8082/scripts/vendor-bundle.js:4667 in check
  http://www.chooseclick.com:8082/scripts/vendor-bundle.js:4923
  http://www.chooseclick.com:8082/scripts/vendor-bundle.js:3918
  http://www.chooseclick.com:8082/scripts/vendor-bundle.js:4973
  http://www.chooseclick.com:8082/scripts/vendor-bundle.js:3843 in each
  http://www.chooseclick.com:8082/scripts/vendor-bundle.js:4972 in emit
  http://www.chooseclick.com:8082/scripts/vendor-bundle.js:4722 in check
  http://www.chooseclick.com:8082/scripts/vendor-bundle.js:4960 in enable
  http://www.chooseclick.com:8082/scripts/vendor-bundle.js:4572 in init
  http://www.chooseclick.com:8082/scripts/vendor-bundle.js:4987 in callGetModule
  http://www.chooseclick.com:8082/scripts/vendor-bundle.js:5395 in completeLoad
  http://www.chooseclick.com:8082/scripts/vendor-bundle.js:5501 in onScriptLoad

` function ensureOriginOnExports(executed, name) {
    var target = executed;
    var key = void 0;
    var exportedValue = void 0;

    if (target.__useDefault) {
      target = target['default'];
    }

    _aureliaMetadata.Origin.set(target, new _aureliaMetadata.Origin(name, 'default'));

    for (key in target) {
      exportedValue = target[key];

      if (typeof exportedValue === 'function') {
        _aureliaMetadata.Origin.set(exportedValue, new _aureliaMetadata.Origin(name, key));
      }
    }

    return executed;
  }
`

and the ensureOriginOnExports is used at the 2 places at line 13767 and 13851 at vendor-bundle.js

file is here http://www.chooseclick.com:8082/scripts/vendor-bundle.js 
if you can try it with phantomjs you will see the error.

**Comment by salihbaki** [comment]
So the solition to my problem was , first i used bluebird polyfill then i had to add create intl.js polyfill under /src/intl.js .

It looks like phantom js looks that file for i18n support.
