### ISSUE TITLE
Hardening DOM changes

### ISSUE THREAD

**Issue by ZoolWay** [aurelia/i18n#230]
**I'm submitting a bug report**

* **Library Version:**
1.6.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.1.2

* **NPM Version:**
5.0.4

* **JSPM**
JSPM 0.17.0-beta.42, SystemJS Loader 0.20.14

* **Browser:**
Chrome 59

* **Language:**
TypeScript 2.3.4

**Current behavior:**
Sometimes it can occur that the plugin tries to manipulate the DOM (loading/updating language) when that DOM node is not available any more (like the user selected something and then _closed  the div_. In that rare race conditions you might encounter:
```
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at I18N.updateValue (.../jspm_packages/npm/aurelia-i18n@1.6.0/i18n.js:193:20)
    at TCustomAttribute.bind (.../jspm_packages/npm/aurelia-i18n@1.6.0/t.js:78:20)
    at Controller.bind (.../jspm_packages/npm/aurelia-templating@1.4.2/aurelia-templating.js:3458:24)
    at View.bind (.../jspm_packages/npm/aurelia-templating@1.4.2/aurelia-templating.js:1462:24)
    at If._runValueChanged (.../jspm_packages/npm/aurelia-templating-resources@1.4.0/if.js:84:19)
    at If.valueChanged (.../jspm_packages/npm/aurelia-templating-resources@1.4.0/if.js:39:31)
    at BehaviorPropertyObserver.selfSubscriber (.../jspm_packages/npm/aurelia-templating@1.4.2/aurelia-templating.js:3702:48)
    at BehaviorPropertyObserver.call (.../jspm_packages/npm/aurelia-templating@1.4.2/aurelia-templating.js:3568:14)
    at BehaviorPropertyObserver.setValue (.../jspm_packages/npm/aurelia-templating@1.4.2/aurelia-templating.js:3548:18)
    at If.descriptor.set [as value] (.../jspm_packages/npm/aurelia-templating@1.4.2/aurelia-templating.js:3657:43)
```

**Expected/desired behavior:**
I would expect the plugin to check for the DOM node existance before.

* **What is the expected behavior?**
It would be better if the plugin checks for the DOM node existance before the update to be failsafe.

* **What is the motivation / use case for changing the behavior?**
While this is not critical, an uncaught exception can be problematic for an application. Here I have a handler for all uncaugt exceptions which tries to handle that and display errors to the user.

**Comment by zewa666** [comment]
Thanks for reporting, yes that's definitely a good idea. So far no issues like that have been reported so it would be great if you could provide a minimal example replicating the problem.

**Comment by ZoolWay** [comment]
I will try to build a minimum example tomorrow.

It might have something to do with translations inside something with `if.bind` when the element vanishes. A colleague of mine gets that error more frequently than me.

**Comment by zewa666** [comment]
That's really much appreciated. Thanks for the help

**Comment by ZoolWay** [comment]
Hm, have you just an empty sample gist.run where aurelia and aurelia-i18n are loaded?

**Comment by zewa666** [comment]
@ZoolWay, Here's an example from another issue: https://gist.run/?id=c7e1c50ba6073c7c27c0fd2bb277e002
Alternatively feel free to just create a new github repo and share the link here, or even just small project, zipped and uploaded.

**Comment by ZoolWay** [comment]
Looks like it is quite difficult to reproduce so I am working on a new github repo.

The problem occurs in `i18n.js` on line 193: `node.removeChild(node._newChild);`
In my case `node._newChild` is not a child of `node`. Instead it is a grandchild and that might be because Kendo UI manipulates the DOM. Will check to defer one or another and otherwise try to come with something up using the opensource variant of Kendo UI.

**Comment by zewa666** [comment]
Sry for putting you in all that trouble but that would be of great help. Looking forward to seeing what you come up with

**Comment by ZoolWay** [comment]
Issue also does not occur when using expression with value converter (i.e. `${'my_const' & t}`) instead of translation attribute (i.e. `t="my_const"`).

**Comment by ZoolWay** [comment]
Okay, I got a repo for you to reproduce the problem, also showing the possible workaround from the comment before:

https://github.com/telecomsoftware/sample-aurelia-i18n-i230

The README covers how to setup and reproduce the problem. It uses Aurelia with SystemJS 0.20 and Kendo UI Core (Open Source, Apache License 2).

**Comment by zewa666** [comment]
First of all thanks for the example. Great to be able to debug and dig into it.

So for your concrete example this line: https://github.com/aurelia/i18n/blob/master/src/i18n.js#L209 would need to be modified to something like this

```
if (node._newChild && node._newChild.parentNode === node) {
  node.removeChild(node._newChild);
}
```

And yes you were right, its due to the fact that Kendos jQuery implementation directly works with the DOM element. I'll add the fix asap, just wanna try out the other attribute variants as well.

Thanks again for reporting the issue 👍

**Comment by ZoolWay** [comment]
Happy to help!
