### ISSUE TITLE
Workaround for allowSyntheticDefaultImports = true

### ISSUE THREAD

**Issue by josundt** [aurelia/i18n#236]
In aurelia-i18n@2.0.0, in the typings file (node_modules/aurelia-i18n/dist/aurelia-i18n.d.ts)  on **line 2**:

```typescript
import i18next from 'i18next';
```

This line causes typescript compile errors if your project's tsconfig.json has not been explicitly configured to allow synthetic default imports.

```
{
    "compilerOptions": {
        "allowSyntheticDefaultImports": true // Required compiler option to make aurelia-i18n work
    }
}
```

This constraint could easily have been avoided by simply changing the line to

```typescript
import * as i18next from 'i18next';
```

Can you please fix this?
I believe this may complicate things for many developers trying to use the plugin...

**Comment by zewa666** [comment]
The thing is that this is the approach how it's done with es6. As such Typescript, being the superset and not the base, it's needed to do that so that both worlds are kinda happy.

**Comment by josundt** [comment]
My suggested change is 100% ES6 module syntax compliant.
```typescript
import * as i18next from 'i18next';
```
This is the expected syntax when importing the complete module content.
This is what you want when importing i18next.

The current import statement in aurelia-i18n@2.0.0...
```typescript
import i18next from 'i18next';
```
...assumes that i18next has a **default** export, which is not the case.

(The error message I get when building with WebPack is that i18next has no default export. 
When setting allowSyntheticDefaultImports to true, the problem is solved).

Ref:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import
http://2ality.com/2014/09/es6-modules-final.html

Your current import statement syntax is actually NOT ES6 modules spec compliant.
TypeScript allows you to import the complete module content using the syntax for importing the default export when the allowSyntheticDefaultImports is set to true. But this is a TypeScript thing - which actually is not ES6 modules spec compliant.

I am sure one can make the import statement work the way it is today if the AMD loader (RequireJS/JSPM etc) configuration is configured in such a way.

So correct me if I am wrong, but what you are saying is actually in reality the other way around. My suggested change is ES6 modules syntax compliant, the current import statement is not (even though TypeScript may allow it with the correct compiler options).

**Comment by zewa666** [comment]
So you essentially suggest switching [this line](https://github.com/aurelia/i18n/blob/master/src/i18n.js#L3) to the alias import? Hmm, well it'd be definitely worth a try. Can you create a PR and see whether thats all thats needed?

**Comment by josundt** [comment]
Please see my pull request. It should solve the problem.

**Comment by zewa666** [comment]
I've changed the title to fit your recent findings of the PR.

**Comment by gheoan** [comment]
This can also be fixed by switching the transpiler from babel to typescript, correct?

**Comment by zewa666** [comment]
For the whole plugin? Yes pretty likely that would solve the issue as well.

**Comment by josundt** [comment]
This is as far as I can tell an issue that ideally should be taken care of by the "babel-dts-generator" plugin. At transpile time, Babel can distinguish CommonJS source modules from other module types, and "babel-dts-generator" should translate the import statements for CommonJS modules to TypeScript compliant import statements.
I just mention in case someone can follow it up...
