### ISSUE TITLE
error after updating aurelia mid-october 2015

### ISSUE THREAD

**Issue by stephenlautier** [aurelia/i18n#24]
Hi,

After updating Aurelia to latest (Mid-October 2015), I've been getting errors caused by unsubscribe, this is due to a breaking change in Aurelia as specified.
> The EventAggregator now returns a subscription object from its subscribe method. The subscription has a dispose method to unsubscribe from the original event.
http://blog.durandal.io/2015/10/13/aurelia-mid-october-2015-releases-performance-and-portable-javascript/

So any event aggregator subscription has to be disposed by `this.subscription.dispose();` instead of `this.subscription();`
https://github.com/aurelia/i18n/blob/b3fdc4acdea1178ffb4e71c90ab1162a2e7fa2ec/src/t.js#L75

**Comment by stephenlautier** [comment]
Added fix @ https://github.com/aurelia/i18n/pull/25

**Comment by zewa666** [comment]
this should be fixed now with the latest release. Once again also thanks for your help and reporting the issue :+1:
