### ISSUE TITLE
i18n breaks for attribute t.bind="(integer variable)"

### ISSUE THREAD

**Issue by lstarky** [aurelia/i18n#251]
**I'm submitting a bug report**

* **Library Version:**
2.1.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.1.0

* **NPM Version:**
5.0.3

* **JSPM OR Webpack AND Version**
webpack 3.5.5

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
An accidental use of the T Attribute (like `<p t.bind="myVar"></p>`) breaks when `myVar` is an integer type.

**Expected/desired behavior:**
The T Attribute should first convert anything to a string before using it, since it expects strings.

* **What is the motivation / use case for changing the behavior?**
Better error handling.

**Comment by zewa666** [comment]
Thanks for reporting. Will be fixed with the next release

**Comment by zewa666** [comment]
@lstarky a new version has been released with the bug fix. Please reopen if it still doesn't work for your
