### ISSUE TITLE
i18n dot in translation string cut from the result

### ISSUE THREAD

**Issue by Akiyamka** [aurelia/i18n#255]
I'm submitting a bug report

* **Library Version:**
1.1.1.2
**Please tell us about your environment:**
* **Operating System:**
Linux (Manjaro)
* **Node Version:**
8.9.4
* **NPM Version:**
5.6.0

* **JSPM OR Webpack AND Version**
JSPM 0.16.53 

* **Browser:**
all 

* **Language:**
ESNext

**Current behavior:**
i18n dot in translation string cut from the result. Example: 
  "foo_bar_baz": "12.12...12" render as "121212"

* **What is the expected behavior?**
must render as "12.12...12"

**Comment by zewa666** [comment]
Wow interesting, can you create a minimal example reproducing the issue for download?

**Comment by Akiyamka** [comment]
Sorry, the reason was not in the translation plugin, the issue can be closed
