### ISSUE TITLE
i18next overriding Aurelia binding

### ISSUE THREAD

**Issue by Rutulpatel7077** [aurelia/i18n#263]
`<p   i18n="base-msrp" >
            <span>${ basePrice }</span>
        </p>`

It is only giving i18next part but not basePrice binding of aurelia.

**Comment by Alexander-Taran** [comment]
By design
http://aurelia.io/docs/plugins/i18n#using-the-plugin
basically i18n used like that will set the text contents of `<P>`

**Comment by Rutulpatel7077** [comment]
@Alexander-Taran   So is there any solution of it ? to use span in <p> with i18n ?

**Comment by Alexander-Taran** [comment]
You might want to read the docs.. there are a lot of solutions..

**Comment by zewa666** [comment]
As Alex mentioned the docs can tell you about different ways to do it. Either by passing vars to the attribute approach or using the tbindingbehavior.

**Comment by Rutulpatel7077** [comment]
`<p i18n="[prepend]base-msrp" > <span>${ basePrice }</span> </p>` .  This Works!  Thanks guys!

**Comment by Alexander-Taran** [comment]
`<span>` is not needed btw

**Comment by Rutulpatel7077** [comment]
@Alexander-Taran  How! can you please explain a little bit more sir

**Comment by Rutulpatel7077** [comment]
@Alexander-Taran  Sure! I will join. btw Thanks for your wonderful help. all of you!

**Comment by Alexander-Taran** [comment]
@Rutulpatel7077 
> How! can you please explain a little bit more sir
I didn't understand the question. sorry
