### ISSUE TITLE
t attribute: optional graceful fallback when: when key is missing, don't replace innerHtml

### ISSUE THREAD

**Issue by migajek** [aurelia/i18n#267]
**I'm submitting a feature request**

* **Library Version:**
2.1.2

please consider adding the configurable graceful fallback for missing keys when using t attribute, as discussed in aurelia forums 
https://discourse.aurelia.io/t/i18n-t-attribute-dont-translate-when-a-key-is-missing/1123/2

**Comment by zewa666** [comment]
I guess same should apply for prepend and append right?

**Comment by migajek** [comment]
for consistency - I'd say so. But to be honest I don't use any of these

**Comment by zewa666** [comment]
@migajek ok I think the linked commit should do so. There should be now a console.warn with the text
```
Couldn't find translation for key: ${key}`
```

where key is the missing key. To turn on this feature you'd have to pass in `skipTranslationOnMissingKey: true` during plugin initialization.

**Comment by migajek** [comment]
perfect, thank you. I'll give it a shot with a next release !
