### ISSUE TITLE
Jibberish code snippet in article

### ISSUE THREAD

**Issue by davidtimovski** [aurelia/i18n#269]
There seems to be an issue with the article. This is what I'm seeing:

![capture](https://user-images.githubusercontent.com/25406486/39702306-a3b16ab4-5204-11e8-82cf-6b0baa27bf4a.PNG)

Looks like it may be from [this commit](https://github.com/aurelia/i18n/commit/09060e110049b60a98a30a2fafa779bc30e19e22) (an extra bracket at line 344) though I don't know why that would cause the code snippet to break in the UI.

**Comment by zewa666** [comment]
@eisenbergeffect can you take a look at this one?

**Comment by EisenbergEffect** [comment]
Looks like there are multiple bugs in the latest version of that document. I've fixed the one above locally but there are other issues. I'll work on getting it done this evening.

**Comment by EisenbergEffect** [comment]
I've pushed the fixes. Site deploy is in progress.
