### ISSUE TITLE
Article not the same as one on aurelia.io

### ISSUE THREAD

**Issue by davidtimovski** [aurelia/i18n#270]
I was under the impression that the [article](https://github.com/aurelia/i18n/blob/master/doc/article/en-US/i18n-with-aurelia.md) was the source for the one at [https://aurelia.io/docs/plugins/i18n/](https://aurelia.io/docs/plugins/i18n/) but it doesn't look to be the same.

I had a small fix merged into it a while back and I just noticed the article at aurelia.io doesn't reflect the fix. In fact, it seems quite different. Am I wrong about the articles or is just aurelia.io rarely updated?

**Comment by zewa666** [comment]
Should be fixed now. The update of the docs happens manually so it could be some parts got missed.
