### ISSUE TITLE
Bundle doc not up-to-date

### ISSUE THREAD

**Issue by jdonzallaz** [aurelia/i18n#285]
**I'm submitting a documentation error**

Hello,
In the documentation to *Bundle Translation Files* with the cli, the watch task must be added to the new `watch.ts` file, and not in `run.ts`:
```ts
import processLocales from './process-locales';
// ...
let watches = [
  // ...
  { name: 'locales', callback: processLocales, source: project.localesProcessor.source }
];
```

With aurelia-cli: 1.0.0-beta.1

**Comment by zewa666** [comment]
thank you @jdonzallaz
