### ISSUE TITLE
Path in typings.json no longer targeting aurelia-i18n.d.ts

### ISSUE THREAD

**Issue by henrikroschmann** [aurelia/i18n#290]
**I'm submitting a bug report**
Path in typings.json no longer targeting aurelia-i18n.d.ts. 6 days ago aurelia-i18n.d.ts was moved out from the typings folder to the root in the dist folder. 

**Current behaviour:**
typings ERR! message Unable to read typings for "aurelia-i18n". You should check the entry paths in "typings.json" are up to date
typings ERR! caused by https://raw.githubusercontent.com/aurelia/i18n/master/dist/typings/aurelia-i18n.d.ts/index.d.ts responded with 404, expected it to equal 200

**Comment by henrikroschmann** [comment]
typings.json
{
  "name": "aurelia-i18n",
  "main": "dist/typings/aurelia-i18n.d.ts"
}

It should say 
{
  "name": "aurelia-i18n",
  "main": "dist/aurelia-i18n.d.ts"
}

**Comment by bigopon** [comment]
@henrikroschmann Would be nice if you could create a PR for it 👍

**Comment by zewa666** [comment]
PR merged
