### ISSUE TITLE
Bundled translation files

### ISSUE THREAD

**Issue by RWOverdijk** [aurelia/i18n#30]
Hello,

It looks like aurelia-i18n doesn't use bundled translation files. I have it registered using the text plugin.

**Comment by zewa666** [comment]
I guess this changes with the new version using i18next v2. Can you replicate the issue over here as well @RWOverdijk?

**Comment by RWOverdijk** [comment]
I no longer need this functionality, and think it's wise to not bundle translations at all. Here are some reasons:

- You'll have to either force the user to download all translations (in one big bundle), or make a bundle per language. Both aren't ideal.
- You'll take away the freedom from the translators, and force yourself to re-bundle, and re-deploy with every translation made (unless you automate it, which can be quite some work for something this small).
- You can re-use the translation files if you serve them (and thus don't bundle them).
- Adding new languages can be done dynamically (by the translators for instance) without having to re-bundle and re-deploy.
- Having 1 extra file to download is not a bad thing, and the browser will (when configured properly) cache them anyway.

This is my personal preference.

**Comment by zewa666** [comment]
I personally would totally agree with your points, just wasn't sure like you whether there might be a different use case. Lets keep it as you said and reopen this if needed

**Comment by gronostajo** [comment]
For anyone trying to bundle translations in a JSPM/SystemJS setup: you're probably using `i18next-xhr-backend` which is unaware of bundles and attempts to pull translation files separately. Defining custom XHR function should do the trick:

```
function translationLoader(url, options, callback, data) {
  SystemJS.import(url + '!text').then(json => {
    callback(json, {status: '200'})
  }).catch(error => {
    callback(null, {status: '404'});
  });
}

export function configure(aurelia: Aurelia) {
  aurelia.use
    .standardConfiguration()
    .plugin('aurelia-i18n', (instance) => {
      instance.i18next.use(I18nBackend);
      return instance.setup({
        backend: {
          loadPath: 'locales/{{ns}}/{{lng}}.json',
          ajax: translationLoader
        },
[...]
```

(you may have to update `loadPath`, paths will now be resolved relatively to paths provided in `config.js`)

There's a similar guide for Webpack in [backend's readme](https://github.com/i18next/i18next-xhr-backend#usage-with-webpack).

**Comment by zewa666** [comment]
Meanwhile there is a custom Aurelia Backend loader doing exactly this. Its not released yet but you can find it in the master branch. As soon as the docs for this are in place its gonna be released
