### ISSUE TITLE
i18n stopped working

### ISSUE THREAD

**Issue by lares83** [aurelia/i18n#32]
After pre beta update loading i18n cause that whole application is not being bootstrap.
I'm getting this error in console

```Unhandled promise rejection TypeError: resources.getAttribute is not a function(…)(anonymous function) @ es6.promise.js:138
es6.promise.js:138 Unhandled promise rejection TypeError: resources.getAttribute is not a function(…)(anonymous function) @ es6.promise.js:138```

When I remove from main.js file
``` 
aurelia.use
.plugin('aurelia-i18n', (instance) => {
        // adapt options to your needs (see http://i18next.com/pages/doc_init.html)
        instance.setup({
          resGetPath : 'locale/__lng__/__ns__.json',
          lng : 'de',
          attributes : ['t','i18n'],
          getAsync : true,
          sendMissing : false,
          fallbackLng : 'en',
          debug : false
        });
      });

everything is working fine.

**Comment by JeroenVinke** [comment]
duplicate of https://github.com/aurelia/i18n/issues/29, and a workaround is to change [this](https://github.com/JeroenVinke/i18n/commit/487c49cc30a404f74816dcfbd3afced33c4f689b) in `jspm_packages/github/aurelia/i18n@0.3.0/index.js`

**Comment by lares83** [comment]
Your fix works great:) Thanks. I'll close ticket as it's a duplicate of #29.
