### ISSUE TITLE
aurelia-i18n.d.ts(6,10): error TS2614: Module '"../../i18next"' has no exported member 'i18next'

### ISSUE THREAD

**Issue by CedricMalfreytBL** [aurelia/i18n#327]
**I'm submitting a bug report**

* **Library Version:**
3.1.2 and 3.1.3

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
12.18.3

* **NPM Version:**
6.14.4

* **JSPM OR Webpack AND Version**
webpack 4.42.0

* **Browser:**
all

* **Language:**
TypeScript 4.0.2

**Current behavior:**
When building a project whith aurelia-i18n v 3.1.2 ou > the following error occurs :

aurelia-i18n.d.ts(6,10): error TS2614: Module '"../../i18next"' has no exported member 'i18next'

**Expected/desired behavior:**

* **What is the expected behavior?**

In aurelia-i18n v3.1.1 and <, this error didn't occur. I expect the error to not occur in v3.1.2 and >.

* **What is the motivation / use case for changing the behavior?**

I think we all want our code to compile.

**Comment by zewa666** [comment]
Yep sorry PR is there just waiting for a quick review https://github.com/aurelia/i18n/pull/326

**Comment by zewa666** [comment]
Released v3.1.4 which should fix this. Going to close this ping again if you still encounter issues

**Comment by CedricMalfreytBL** [comment]
Hi @zewa666 , just updated to 3.1.4, the issue no longer exists.

Thank you 👍
