### ISSUE TITLE
Applying a Value Converter to a Translated value.

### ISSUE THREAD

**Issue by ChrisMancini** [aurelia/i18n#33]
I want to apply a value converter (simple converter to append a ":" to the end of the field) to a translated field.

If I do this:

````HTML
<td t.bind="label | labelFormat"></td>
````

As one would expect the converter is applied to the label before the translation occurs, therefore it doesn't find the key in the translation table.

Any suggestions as to how to apply the converter (in HTML, not the viewmodel) to the value after it has been translated?

I am currently doing it this way:

````HTML
<td t="[prepend]${label}">:</td>
````

But would prefer to use the converter.

**Comment by nomack84** [comment]
Do you know the `t` converter? Just try: 
```html
<td>${ label | t | labelFormat }</td>
```
Regards

**Comment by ChrisMancini** [comment]
Exactly what I was looking for thanks!  (I did know about the t converter (am using it in other places), didn't know you could chain converters though!)
