### ISSUE TITLE
After bundle translations are not working

### ISSUE THREAD

**Issue by lares83** [aurelia/i18n#34]
Hi,
When I bundle my project translations are not being displayed. I'm using the aurelia-beta-01.

**Comment by moshensky** [comment]
same here, any resolution

**Comment by moshensky** [comment]
I had the same issue. After turning debugging of i18n to true, I saw that I used t value converter before resources files got loaded. Setting     getAsync : false solved issue for me.

**Comment by zewa666** [comment]
@lares83 can you confirm that @moshensky's workaround works for you as well?

**Comment by lares83** [comment]
@zewa666 @moshensky's workaround works well for me, thanks

**Comment by zewa666** [comment]
ok, I've added some info about this in the README file. Thanks @moshensky for the solution

**Comment by AdamWillden** [comment]
@zewa666 I'm having this issue with v2 but the work around option was removed in v2. Don't suppose you have any ideas?
