### ISSUE TITLE
Error: Error invoking TaskQueue. Check the inner error for details.

### ISSUE THREAD

**Issue by ehudkaldor** [aurelia/i18n#40]
hope you can help direct me. i am trying to write an Aurelia app, with i18n. I follow the instructions, but any time I add I18N to the initialization, i get a long, weird exception:
Unhandled promise rejection Error: Error invoking TaskQueue. Check the inner error for details.
------------------------------------------------
inner error: makeRequestFlushFromMutationObserver@http://localhost:8000/jspm_packages/npm/aurelia-task-queue@1.0.0-beta.1/aurelia-task-queue.js:13:20
TaskQueue@http://localhost:8000/jspm_packages/npm/aurelia-task-queue@1.0.0-beta.1/aurelia-task-queue.js:59:41
invoke@http://localhost:8000/jspm_packages/github/aurelia/dependency-injection@0.12.0/aurelia-dependency-injection.js:334:14
invoke@http://localhost:8000/jspm_packages/github/aurelia/dependency-injection@0.12.0/aurelia-dependency-injection.js:309:155
invoke@http://localhost:8000/jspm_packages/github/aurelia/dependency-injection@0.12.0/aurelia-dependency-injection.js:557:16
get@http://localhost:8000/jspm_packages/github/aurelia/dependency-injection@0.12.0/aurelia-dependency-injection.js:145:27
get@http://localhost:8000/jspm_packages/github/aurelia/dependency-injection@0.12.0/aurelia-dependency-injection.js:488:18
invoke@http://localhost:8000/jspm_packages/github/aurelia/dependency-injection@0.12.0/aurelia-dependency-injection.js:354:23
invoke@http://localhost:8000/jspm_packages/github/aurelia/dependency-injection@0.12.0/aurelia-dependency-injection.js:309:155
invoke@http://localhost:8000/jspm_packages/github/aurelia/dependency-injection@0.12.0/aurelia-dependency-injection.js:557:16
get@http://localhost:8000/jspm_packages/github/aurelia/dependency-injection@0.12.0/aurelia-dependency-injection.js:145:27
get@http://localhost:8000/jspm_packages/github/aurelia/dependency-injection@0.12.0/aurelia-dependency-injection.js:488:18
initialize@http://localhost:8000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1/aurelia-templating.js:3154:30
initialize@http://localhost:8000/jspm_packages/github/aurelia/templating@0.17.0/aurelia-templating.js:2337:7
initialize@http://localhost:8000/jspm_packages/github/aurelia/templating@0.17.0/aurelia-templating.js:2256:9
importViewResources/<@http://localhost:8000/jspm_packages/github/aurelia/templating@0.17.0/aurelia-templating.js:2617:11
l/</h@http://localhost:8000/jspm_packages/npm/core-js@1.2.6/client/shim.min.js:1773:66
l/<@http://localhost:8000/jspm_packages/npm/core-js@1.2.6/client/shim.min.js:1778:19
e@http://localhost:8000/jspm_packages/npm/core-js@1.2.6/client/shim.min.js:1958:55

Stack trace:
AggregateError@http://localhost:8000/jspm_packages/github/aurelia/pal@0.3.0/aurelia-pal.js:20:13
invoke@http://localhost:8000/jspm_packages/github/aurelia/dependency-injection@0.12.0/aurelia-dependency-injection.js:559:15
get@http://localhost:8000/jspm_packages/github/aurelia/dependency-injection@0.12.0/aurelia-dependency-injection.js:145:27
get@http://localhost:8000/jspm_packages/github/aurelia/dependency-injection@0.12.0/aurelia-dependency-injection.js:488:18
invoke@http://localhost:8000/jspm_packages/github/aurelia/dependency-injection@0.12.0/aurelia-dependency-injection.js:354:23
invoke@http://localhost:8000/jspm_packages/github/aurelia/dependency-injection@0.12.0/aurelia-dependency-injection.js:309:155
invoke@http://localhost:8000/jspm_packages/github/aurelia/dependency-injection@0.12.0/aurelia-dependency-injection.js:557:16
get@http://localhost:8000/jspm_packages/github/aurelia/dependency-injection@0.12.0/aurelia-dependency-injection.js:145:27
get@http://localhost:8000/jspm_packages/github/aurelia/dependency-injection@0.12.0/aurelia-dependency-injection.js:488:18
initialize@http://localhost:8000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1/aurelia-templating.js:3154:30
initialize@http://localhost:8000/jspm_packages/github/aurelia/templating@0.17.0/aurelia-templating.js:2337:7
initialize@http://localhost:8000/jspm_packages/github/aurelia/templating@0.17.0/aurelia-templating.js:2256:9
importViewResources/<@http://localhost:8000/jspm_packages/github/aurelia/templating@0.17.0/aurelia-templating.js:2617:11
l/</h@http://localhost:8000/jspm_packages/npm/core-js@1.2.6/client/shim.min.js:1773:66
l/<@http://localhost:8000/jspm_packages/npm/core-js@1.2.6/client/shim.min.js:1778:19
e@http://localhost:8000/jspm_packages/npm/core-js@1.2.6/client/shim.min.js:1958:55
 shim.min.js:1786:54

my code:

main.js:
```javascript
import 'semantic-ui';
import {I18N} from 'aurelia-i18n';

export function configure(aurelia, I18N) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('aurelia-i18n', (instance) => {
      // adapt options to your needs (see http://i18next.com/pages/doc_init.html)
      instance.setup({
        resGetPath : 'locale/__lng__/__ns__.json',
        lng : 'en',
        attributes : ['t','i18n'],
        getAsync : false,
        sendMissing : false,
        fallbackLng : 'en',
        debug : true,
        ns: {
          namespaces: ['translation','nav'],
          defaultNs: 'translation'
        }
      });
    });


  //Uncomment the line below to enable animation.
  aurelia.use.plugin('aurelia-animator-css');

  //Anyone wanting to use HTMLImports to load views, will need to install the following plugin.
  // aurelia.use.plugin('aurelia-html-import-template-loader')

  aurelia.start().then(a => a.setRoot());
}
```

index.html:
```html
<!doctype html>
<html>
  <head>
    <title>Aurelia</title>
    <link rel="stylesheet" href="styles/styles.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body aurelia-app="main">
    <script src="jspm_packages/system.js"></script>
    <script src="config.js"></script>
    <script>
      System.import('aurelia-bootstrapper');
    </script>
  </body>
</html>```

**Comment by ehudkaldor** [comment]
i have tried it with and without adding I18N as a parameter for configure()

**Comment by zewa666** [comment]
@ehudkaldor may I ask you to try to recreate the issue within this plunker? http://plnkr.co/edit/5vMoxM?p=preview

**Comment by ehudkaldor** [comment]
I am new to plnkr, so not sure if i am doing anything wrong. I put the relevant files in, but i could not save them. i created a new one, but nothing seems to happen. can you check it here?
http://plnkr.co/edit/wiRcGr?p=preview

**Comment by zewa666** [comment]
Just press the fork button, which will create a copy for yourself. Then modify that one and save it.

**Comment by ehudkaldor** [comment]
http://plnkr.co/edit/wiRcGr?p=preview

**Comment by zewa666** [comment]
mmhm not quite that, you really need to leverage the existing structure of the plunker, as it points to hosted config.js entries. Also your translation files are missing.

If that feels like to much crazy work, simply create a github repo with all your sources (of course don't check in npm/jspm folders).

**Comment by ehudkaldor** [comment]
see here:
https://github.com/ehudkaldor/whatsupdoc

**Comment by ehudkaldor** [comment]
anything?

**Comment by zewa666** [comment]
sry it took me so long, was on vacation. The issue you have is that in the meantime there was a new release and it seems you didn't fully update your jspm dependencies. I think this time `jspm update` inside your projects root should help. See here http://blog.durandal.io/2015/12/03/aurelia-patch-updates-2015-12-03/

**Comment by ehudkaldor** [comment]
sorry for the delay (me too). the update indeed solved it. closing.
