### ISSUE TITLE
escape characters in input placeholder translation

### ISSUE THREAD

**Issue by flieks** [aurelia/i18n#42]
hi,

on an input field i want to put translation with special characters. How to do ?

I tried this
```
<input t="[placeholder][html]firstname" type="text">
```
and this
```
<input placeholder="${'[html]firstname' | t" type="text">
```

I'm using aurelia-i18n 0.2.6

thanks 
Felix

**Comment by zewa666** [comment]
could you add an example of what is inside firstname and what you'd expect to have  as placeholder value?

**Comment by zewa666** [comment]
@flieks ping

**Comment by zewa666** [comment]
closing due to non-activity

**Comment by RouR** [comment]
Example
i18n.tr("name", { name: "1'<>22"})
It translates to 1&#39;&lt;&gt;22 instead of 1'<>22

**Comment by RouR** [comment]
Workaround
sometext = $('<textarea />').html(sometext).text();
