### ISSUE TITLE
Interpolation with subobjects doesn't work

### ISSUE THREAD

**Issue by TheGr8Nik** [aurelia/i18n#43]
If we want to interpolate with some sub-object values the resulting string is wrong.

Example:
translation.json
```javascript
{
  "test": {
    "test_string": "This __foo.bar__ is wrong!"
  }
}
```

foobar.js
```javascript
test_string = i18n.tr('test.test_string', {foo:{bar:'correct'}});
```

I tried to find out what is the problem and I found it!
At line 75 of the i18n.js file https://github.com/aurelia/i18n/blob/master/src/i18n.js#L75
the subobjects are converted in object values:

```javascript
{
  foo: {
    bar: 'correct'
  }
}

// is converted in
{
  foo.bar: 'correct'
}
```

But if we give a look to the i18next source code of the master branch https://github.com/i18next/i18next/blob/master/src/i18next.translate.js#L19-L23 we see that when it find a replacement with a keyseparator symbol inside (the dot in the most of cases) it try to search the sub object key property recursively.

The solution is to convert the line 75 of the i18n.js file from
```javascript
return this.i18next.t(key, assignObjectToKeys('', fullOptions));
```
to 
```javascript
return this.i18next.t(key, fullOptions);
```

**Comment by zewa666** [comment]
this should be fixed with the latest release. Please reopen if you still experience issues
