### ISSUE TITLE
Problem with ArrayObserver

### ISSUE THREAD

**Issue by GreenToast** [aurelia/i18n#44]
Hey guys, 

It seems for me that the ArrayObserver has a bug by observing the splice method. If I run the following code with splice the Error below is thrown. If I use the push instead it works pretty fine.

addType(payload) {  
        this.listselected.splice(payload.pos, 0,{_id:payload.id,properties:{name:payload.name}});
        //this.listselected.push({_id:payload.id,properties:{name:payload.name}});
}

Uncaught TypeError: Cannot read property 'overrideContext' of undefined
updateOverrideContexts @ collection-strategy.js:45
handleChanges @ array-collection-strategy.js:66
handleCollectionChanges @ repeat.js:172
call @ repeat.js:62
callSubscribers @ aurelia-binding.js:219
call @ aurelia-binding.js:715
flushMicroTaskQueue @ aurelia-task-queue.js:110
(anonymous function) @ aurelia-task-queue.js:60

**Comment by jdanyow** [comment]
@GreenToast it looks like you're on an old version of Aurelia. Does updating to the latest releases solve this issue?

**Comment by GreenToast** [comment]
Thanks. Yes the Aurelia project.json over yeoman is a few month old . "jspm update" solved it. Sorry, haven't checked that earlier.

**Comment by jdanyow** [comment]
@GreenToast I don't think `jspm update` will get you fully updated.

To force jspm to fully update your project, locate [this section](https://github.com/aurelia/skeleton-navigation/blob/1.0.0-beta.1.0.2/package.json#L61-L75) in your package json and use it to craft a `jspm install` statement.  Here's what the skeleton-navigation project's command to update would be based on [this package.json](https://github.com/aurelia/skeleton-navigation/blob/1.0.0-beta.1.0.2/package.json#L61-L75):

```shell
jspm install aurelia-animator-css aurelia-bootstrapper aurelia-fetch-client aurelia-framework aurelia-history-browser aurelia-loader-default aurelia-logging-console aurelia-router aurelia-templating-binding aurelia-templating-resources aurelia-templating-router bootstrap fetch font-awesome text
```

you should also update systemjs:
```shell
jspm dl-loader --latest
```
