### ISSUE TITLE
Getting 404 error for translation.json even if defaultNs is configured with different file

### ISSUE THREAD

**Issue by valichek** [aurelia/i18n#47]
Error comes out when trying to switch locale.

Here is plunker: http://plnkr.co/edit/NVHURr

Here is config for plugin.
```javascript
{
        resGetPath: '__lng__-__ns__.json',
        lng: 'de',
        attributes: ['t', 'i18n'],
        getAsync: true,
        sendMissing: false,
        fallbackLng: 'en',
        debug: false,
        ns: { 
          namespaces: ['tr','tr1'],
          defaultNs: 'tr'
        }
}
```

**Comment by zewa666** [comment]
interesting ... I think though this is a bug by i18next itself, we're not touching anything there as far as I know.

**Comment by zewa666** [comment]
does this bug still exist in the most recent version? Also note the changed namespace options http://i18next.com/docs/options/

**Comment by zewa666** [comment]
@valichek ping!

**Comment by valichek** [comment]
Bug still exists, so one should avoid this config
https://gist.run/?id=d6eaa855431f4c748df103e2974a3797

**Comment by EisenbergEffect** [comment]
@zewa666 What is the status of this? Can it be closed now?

**Comment by davismj** [comment]
Looks like the bug is still present: http://stackoverflow.com/questions/38508408/i18next-appends-the-default-translation-namespace-to-my-namespaces

**Comment by cerealBoxx** [comment]
Is this bug going to be addressed soon?

**Comment by zewa666** [comment]
@valichek, @davismj, and @cerealBoxx I'm not sure why this happens but it seems to be related to the way, how i18next tries to resolve resources. One of the steps is to look for a fallbackLng including the default namespace called, you guessed it, `translation`, as such the 404 request is happening.

The only way I found to fix this is to set the fallbackLng to false

```
return instance.setup({
      backend: {                        
        loadPath: './locales/{{lng}}/{{ns}}.json', 
      },
      lng : 'de',
      ns: ['foo'],
      defaultNS: "foo",

      attributes : ['t','i18n'],
      fallbackLng : false,  <----- SET THIS TO FALSE TO AVOID A SEARCH FOR translation NS
      debug : false
    });
```

**Comment by cerealBoxx** [comment]
Ok, thank you for the input.

**Comment by rajatsingh1603** [comment]
Is this bug still persist?

**Comment by bigopon** [comment]
Its already closed as complete @rajatsingh1603
