### ISSUE TITLE
Plugin cannot be used without installed babel-runtime

### ISSUE THREAD

**Issue by milunka** [aurelia/i18n#5]
After i have sucessfully installed this plugin i findout that i could not use it.
For some reason almost all files requires babel-runtime but this module isn't between jspm dependecies but only in devDependencies section.

I am thinking that build process is somehow wrong or definition of required dependencies for jspm needs update requirements of this plugin.

**Comment by zewa666** [comment]
Hi there,

Hm not sure whats causing this. Maybe this line, which could be used during the build sequence https://github.com/aurelia/i18n/blob/master/build/babel-options.js#L10

@EisenbergEffect do you have any idea? So far I wasn't able to reproduce this error

**Comment by EisenbergEffect** [comment]
It sounds like a configuration issue. Try removing the runtime from that list. That shouldn't be needed.

**Comment by EisenbergEffect** [comment]
Has this been resolved as a configuration issue. Can this be closed?

**Comment by zewa666** [comment]
I've just tested it today on a completely new machine, where node and everything was installed from scratch. No problems when installing aurelia-i18n. @milunka sorry but I'm not really sure what was causing your issue. Could you try to setup a fresh new skeleton with the latest version and see if it happens again?

**Comment by Souldrinker** [comment]
As far as I can see the issue is that in for example most files in the dist/amd folder you get a lot of defines to babel stuff, for example this:
```
define(['exports', 'babel-runtime/helpers/create-class', 'babel-runtime/helpers/class-call-check', './i18n', 'aurelia-event-aggregator'], function (exports, _babelRuntimeHelpersCreateClass, _babelRuntimeHelpersClassCallCheck, _i18n, _aureliaEventAggregator)
```

In your old aurelia-i18next the babel stuff is not in the defines. As long as the babel stuff is there it seems you need to have babel and babel-runtime defined in your config.js (which seems to get there anyway when you have aurelia-cli imported, but I suppose that's another issue).

**Comment by milunka** [comment]
@zewa666 with skeleton application this issue cannot be duplicated because after provisioning everything for skeleton application you have in jspm folder babel-runtime installed. And as @Souldrinker wrote in his comment, define section from almost every i18n js file requires babel-runtime.
I think that as @EisenbergEffect wrote just remove runtime from babel-options.js and maybe config.js and compiled js files won't need babel-runtime. You could look at that exact change which i made in cloned repository here: https://github.com/milunka/i18n

**Comment by zewa666** [comment]
@Souldrinker, @milunka thanks for clarifying the situation. Didn't thought about you TS guys :)

Next time I'm at my desktop, I'll release a new version. As you @milunka and @EisenbergEffect mentioned, this should fix the issue.

**Comment by zewa666** [comment]
@Souldrinker, @milunka hey guys I've finally managed to push the new version without runtime setting. Could you please give it a try?

**Comment by milunka** [comment]
@zewa666 i tried latest version and it works without problem. I just have one small request could you please create tag 0.1.1 for your latest commit? Otherwise i could not install specific version into my project and i must use master branch.

**Comment by zewa666** [comment]
of course will do. Thanks or checking it out :+1:

**Comment by Souldrinker** [comment]
Thanks for this, but it would also be nice if you while you were at it would have compiled it against the current version of Aurelia libraries so we avoid manually hacking the config.js to avoid forks.

May I ask why some of the libraries like this one and aurelia-validation isn't released in sync with the rest of the aurelia libraries when new "major" (0.x) versions are released now that they are under the aurelia repository?

**Comment by zewa666** [comment]
The problem is simple. Because Im a noob :) will take care of that in future releases

**Comment by Souldrinker** [comment]
hehe, no problem, just asking. I got it working just fine after some minor fiddling with the config.js ;-)
