### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'new this.Intl.DateTimeFormat') in Safari and IE

### ISSUE THREAD

**Issue by valichek** [aurelia/i18n#52]
Getting this error in Safari (osx) and Internet Explorer (windows). Firefox and Chrome are OK.
Looks like `Intl` polyfill not working, it would be nice to have some warning and default handler, but not exception, because it breaks code execution

In https://github.com/andyearnshaw/Intl.js/blob/v0.1.4/Intl.complete.js#L29
Intl is added as `global.Intl`, not `window.Intl` as in aurelia/i18n https://github.com/aurelia/i18n/search?q=this.Intl.DateTimeFormat&type=Code&utf8=✓

Also there is a new version of Intl, so it could be upgraded.

**Comment by valichek** [comment]
Quickfix if someone is suffering

`jspm install intl=github:andyearnshaw/Intl.js@0.1.4`

This code goes somewhere to load first, like App.js
```javascript
import {I18N} from 'aurelia-i18n';
import Intl from 'intl';
...
static inject() { return [I18N]; }

constructor(i18n) {
    if(Intl) {
      i18n.Intl = Intl;
    }
  }
```

**Comment by zewa666** [comment]
@valichek can you try it out with the new version? Maybe this got fixed as well

**Comment by valichek** [comment]
have checked for Safari and it works

**Comment by zewa666** [comment]
cool ok lets close this one, we can reopen it if it fails again

**Comment by mbenedyk** [comment]
I get the same exception when i execute unit test for 'df' by Chutzpah, byt when i run them from browser they are ok

I`m using aurelia-i18n@0.4.10

**Comment by zewa666** [comment]
@mbenedyk should be fixed with the next release

**Comment by valichek** [comment]
@zewa666 Regarding using webpack. `Intl` should be included in packages, so please add some line to docs that we need to require `Intl` module in `main.js` so it should be available for module loader.
```
//main.js
import 'intl';
```

Or maybe another (better?) option is to add some `useIntl.js` to `aurelia-18n`, add intl dependency for npm, in that way I suppose it will be included for AureliaWebpackPlugin that has `includeSubModules` option. But that is just an idea to try. What do you think? @martijnboland

**Comment by martijnboland** [comment]
@valichek intl is a polyfill right? In that case I'd always import it directly in my main.js

**Comment by valichek** [comment]
+ some reference to https://github.com/andyearnshaw/Intl.js#intljs-and-browserifywebpack

**Comment by zewa666** [comment]
Thanks for the info @valichek and @martijnboland. I've updated the README
