### ISSUE TITLE
0.4.5 broken

### ISSUE THREAD

**Issue by doktordirk** [aurelia/i18n#54]
no htmlParamsResource defined 

https://github.com/aurelia/i18n/commit/3fd242f24eb320b2dad9b4ad22048f778635ef66#diff-6b77f8cbb641c01e2d9bc298ee6c76d7R45

**Comment by zewa666** [comment]
damn good catch, sry about that. Wonder why it still worked for me :)
Its fixed with the latest commit.

**Comment by doktordirk** [comment]
jepp. works again with that
