### ISSUE TITLE
Translate input placeholders

### ISSUE THREAD

**Issue by heruan** [aurelia/i18n#58]
Why not to create an attribute binding for translate input placeholders?

Something like:
```html
<input type="text" placeholder.i18n="form.input.username">
```

Options could be passed with a syntax like:
```html
<input type="text" placeholder.i18n="form.input.username | defaultValue: 'Username'">
```

**Comment by zewa666** [comment]
I'm not sure this is the best approach since it introduces even more ways to translate stuff. How about instead we create an additional attribute like `[placeholder]`? https://github.com/aurelia/i18n#specifying-attributes

**Comment by heruan** [comment]
I think this way would be cleaner and more extendable, using a more structured _Aurelia syntax_ (like other bindings). The `t="[placeholder]my.key"` surely would work, but how to specify options like default values, context or plurals?

**Comment by RWOverdijk** [comment]
Is it currently at all possible to translate placeholders?

**Comment by zewa666** [comment]
@RWOverdijk of course, just use either the ValueConverter or the BindingBehavior

```
<input placeholder="${'your-key' | t}">
```

**Comment by DerAlbertCom** [comment]
<input t="[placeholder]theKey"/> works in rc.1

**Comment by EisenbergEffect** [comment]
@zewa666 Update?

**Comment by zewa666** [comment]
@EisenbergEffect yep the placeholder can now be addressed using the attribute approach. I'm do understand the benefit of what @heruan proposes, yet I feel that adding a 4th declarative approach to perform translations feels a bit like a overkill.
Current state of affairs is:

ValueConverters for onetime simple translations
BindingBehaviours for auto-updating translations
TAttribute as a full-fleged / fancy-pants approach.

I'll close this issue for now but if there is really a need for it we can later revise it again
