### ISSUE TITLE
setTimeout in TCustomAttribute causes annoying 'blink' in browser

### ISSUE THREAD

**Issue by kaarholt** [aurelia/i18n#59]
My view is first rendered with initial texts, then (one tick later) texts are replaced by i18n texts. This causes a visible 'jump' of content in the browser, because elements might need less or more space.

The reason is the usage of setTimeout in https://github.com/aurelia/i18n/blob/master/src/t.js line 50 and 62. QUESTION: Why are these timeouts there?

Using i18n in text-nodes instead of attributes does not have the setTimeout issue, and would of course be a solution to my problem. Extending the view with BaseI18N also solves the problem because i18n.updateTranslations is called. But it requires a lot of extra setup code for my view-models. 

It would be nice if translating via html attributes worked out of the box.

**Comment by EisenbergEffect** [comment]
@zewa666 I'd like to understand why those setTimeout calls are there too. We definitely don't want to delay things in the binding process that affect rendering since this will cause performance issues and, as mentioned above, UX problems.

**Comment by zewa666** [comment]
tbh I have absolutely no clue why I needed those timeouts, especially why there is a second one nested below. I remember vaguely there was some timing issue with binding, but maybe that's gone by now. Will have to check that again

**Comment by EisenbergEffect** [comment]
There may have been a bug in subscribing to the value property of a custom attribute early on. That was fixed though.

**Comment by zewa666** [comment]
ok, sounds good will try to fix it asap

**Comment by zewa666** [comment]
ok seems that it works without using the timeouts. All tests passed and I couldn't find an obvious issue in my test candidates.
This will go online with the next release

**Comment by zewa666** [comment]
This was released, if you @kaarholt still experience any issues we can reopen this again
