### ISSUE TITLE
How to refresh translated view when using converters?

### ISSUE THREAD

**Issue by valichek** [aurelia/i18n#6]
Switching locale doesn't affect the view when I use TValueConverter, but values translated with `t='myProp'` do change.
```javascript
this.ea.subscribe('i18n:locale:changed', payload => {
  i18n.updateTranslations(element);
});
```
How to trigger translation with converters?

**Comment by valichek** [comment]
Well, after playing with ValueConverters I have found the solution. Not beautiful, but works.
Here is example for TValueConverter.
```
test="${'form-account.choose-avatar' | t : {dummy: currentLocale}}"
```
I change currentLocale value on `i18n:locale:changed` event and it triggers reavaluating of test property.

**Comment by zewa666** [comment]
Hi there, yes you're right there is no nice approach available at the moment. There is though a new feature planned called ValueConverter signaling, which would allow us to hint VCs about changes and thus let them re-evaluate their inputs. This will help, but we have to wait until its complete

**Comment by EisenbergEffect** [comment]
@zewa666 I wonder if we could bake i18n into the templating engine more deeply. Could we come up with something like we have for animation? Could there be a base abstraction somewhere that we could tie in that this library could implement to plug things in more deeply?

**Comment by zewa666** [comment]
@EisenbergEffect what would be the benefit? Can't wrap my head around where this might come in handy. In case of the Animator we needed it actually for certain things to get automatically called. Not so for I18N as far as I can think. I'd be happy for an example.

**Comment by EisenbergEffect** [comment]
Well, I was thinking about this specific case. What if string interpolation expressions could automatically be updated when the culture changed, for example?

**Comment by zewa666** [comment]
That'd be an interesting approach, although I fear that we could run into a lot of edge cases with that. As an example what if I don't want to update every binding as for performance reasons but just a specific section?

But yeah I see what you're talking about. I'm just not sure how good/bad that tighter coupling together with Aurelia's core plays out.

**Comment by EisenbergEffect** [comment]
I don't know either, but I wanted to throw it out there so you could ponder it and see if anything would make sense.

**Comment by zewa666** [comment]
This is now handled with the new TBindingBehavior. Updated readme follows soon.
