### ISSUE TITLE
Router.Title translations for the title of the page

### ISSUE THREAD

**Issue by steamonimo** [aurelia/i18n#60]
In the router configuration you can give a title to the route:

`config.map([ { route: ['xy'], name: 'xy', moduleId: 'xy', title: 'MenuXy' } ... ]`

This route can be translated by i18n in the HTML code - for example for a nav bar

`<li repeat.for="row of router.navigation" class="${row.isActive ? 'active' : ''}">`
`<a href.bind="row.href" t="${row.title}">${row.title}</a>`
`</li>`

However the browser title of the tab/page will still be 'MenuXy'. Aurelia should adjust the behaviour of the title such that it will be translated too. Perhaps some sort of mechanism like t="MenuXy" can be implemented for the title too. In my scenario it is no option to directly translate in the config phase because the language can be switched dynamically by the user. Thanks.

**Comment by jedd-ahyoung** [comment]
@Aaike This issue may need to be tagged as a feature request.

**Comment by vbnewb** [comment]
I just used the translate function in the router config.map

         { route: ['', 'home'],name: 'home',   moduleId: './home',   nav: true, title: this.i18n.tr('nav:Home'), icon:'fa-dashboard',auth:true },

**Comment by mttmccb** [comment]
Just looking at this myself, it is possible to be able to bind it? I'm attempting to pass the i18n reference as part of the config settings with no joy.

**Comment by mttmccb** [comment]
Nevermind, t.bind does work :)

**Comment by johnraz** [comment]
@mttmccb do you mind giving an example? Thx!

**Comment by Halvotec** [comment]
I think what he meant was using 

`t.bind="row.title"`
instead of 
`t="${row.title}"`

In the given example from steamonimo this would then be:

`<li repeat.for="row of router.navigation" class="${row.isActive ? 'active' : ''}">
<a href.bind="row.href" t.bind="row.title">${row.title}</a>
</li>`

**Comment by steamonimo** [comment]
@Halvotec You approach does not work. t.bind="row.title" will just search for row.title in the translation file. My example above works as expected. So the navigation elements (li elements) will be correctly translated. The problem is that the main title of the page shown in the tabs will just show "MenuXy" but not the translation for "MenuXy".

**Comment by stefan505** [comment]
@steamonimo I have exactly the same problem and need. Have you had any joy with this in the meantime?

**Comment by leye0** [comment]
@mttmccb do you mind giving an example? Thx!

**Comment by stsje** [comment]
Also tracked in the Router repository https://github.com/aurelia/router/issues/343

**Comment by EisenbergEffect** [comment]
I'm going to close this as a duplicate since we've already got the feature requeston the router. I think we just need to implement a function that each "title" value for each route gets passed through when it builds the title. This would allows the developer to supply any function they want, including one that invokes i18n APIs.
