### ISSUE TITLE
Error installing current update 0.4.7

### ISSUE THREAD

**Issue by cdennig** [aurelia/i18n#63]
Hi there,

when trying to update to the current version of aurelia-i18n (0.4.7), jspm reports the following error:

```
warn Error on processPackageConfig
     Package.json dependency Intl.js set to github:andyearnshaw/Intl.js@^0.1.4, which is not a valid dependency format for npm. 
It's advisable to publish jspm-style packages to GitHub or another registry so conventions are clear.

err  Error processing package config for npm:aurelia-i18n.
```

The package is not updated.

Please have a look at it.

Many thanks,
Chris

**Comment by EisenbergEffect** [comment]
Yes, as reported in the gitter chat room, there's an issue with the package.json file right now that we are trying to resolve. This relates to jspm. Please do not update until the fix is announced. We are working on it.
