### ISSUE TITLE
development/testing setup problem

### ISSUE THREAD

**Issue by k2s** [aurelia/i18n#68]
I wanted to run `karma start`, but I can't.

What I did:
```
npm install
npm install -g gulp
npm install -g karma-cli
npm install -g jspm
jspm install
karma start
```

What problems I have:
* `npm install` doesn't work because of `"i18next": "i18next/i18next@^1.9.0"` in `package.json`, it works after I replace it with `"i18next": "^1.9.0"`
* `karma start` errors all tests because config.js points to wrong versions: `WARN [web-server]: 404: /base/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.1.2.js`
* after `jspm update`, `karma start` breaks with message `Error: EMFILE: too many open files,`

**Comment by k2s** [comment]
was able to solve `Error: EMFILE: too many open files` problem by editing /etc/security/limits.conf according to this article https://easyengine.io/tutorials/linux/increase-open-files-limit/

still the tests are not ececuted

**Comment by zewa666** [comment]
which version of jspm are you using @k2s?

**Comment by k2s** [comment]
I don't think it is problem with jspm. The `"i18next": "i18next/i18next@^1.9.0"` is wrong in package.json section `dependencies` which is not processed by jspm, but npm.

But I tried jspm@0.16.25, jspm@0.16.27 and jspm@0.16.29.

**Comment by doktordirk** [comment]
try:
npm install jspm@0.16.15 --save
npm prune
npm install
delete the jspm_packages folder rm -rf ./jspm_packages !!!
delete the map entry in config.json !!!
jspm install

**Comment by k2s** [comment]
```
> jspm -v
0.16.15
Running against local jspm install.
> npm prune
> npm install
npm ERR! addLocal Could not install /tmp/i18n/i18next/i18next@^1.9.0
npm ERR! Linux 4.4.1-2-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v5.6.0
npm ERR! npm  v3.7.3
npm ERR! path /tmp/i18n/i18next/i18next@^1.9.0
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/tmp/i18n/i18next/i18next@^1.9.0'
npm ERR! enoent ENOENT: no such file or directory, open '/tmp/i18n/i18next/i18next@^1.9.0'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/i18n/npm-debug.log
```

**Comment by doktordirk** [comment]
ah right. my suggestion only fixes jspm issues. yours is with npm. hmm

**Comment by doktordirk** [comment]
@k2s but you had npm issues fixed above.so i guess if you npm install as you did and then jspm@0.16.15 install with no jspm folder and the map entry cleared it might work

**Comment by zewa666** [comment]
guess this should be fixed by now, I'll reopen if issues are still existing. As mentioned it works with jspm@0.16.15
