### ISSUE TITLE
IOS Plugin Loading

### ISSUE THREAD

**Issue by vbnewb** [aurelia/i18n#69]
Team,
My site no longer loads if I attempt to use the aurelia-i18n plugin from an iphone.

The final console entry is :
DEBUG [aurelia] , Loading plugin aurelia-i18n.

It should soon be followed by:
DEBUG [aurelia],Configured plugin aurelia-i18n.

But the configured line never gets logged and it appears that no other actions take place after this and aurelia just stops loading.

I tried a few things like not using bundles and modifying the async flag in the configuration for i18n but nothing seems to work. As soon as i remove the plugin the site functions properly again on iphone

**Comment by fabioluz** [comment]
Put this before all other scripts in your index.html and tell me if it works

    <script src="//cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.en"></script>

**Comment by zewa666** [comment]
Does this still exist with the latest release @vbnewb ?

**Comment by Jenselme** [comment]
I had a similar issue on my SPA with the latest release of this plugin on Safari. Here is the message I got in the console:
![safari-aurelia-i18n](https://cloud.githubusercontent.com/assets/6643536/15791448/b1f3d3ca-29d7-11e6-9f70-4509dcb75818.png)

I solved it by using the [Intl.js](https://github.com/andyearnshaw/Intl.js/) polyfill. To do so, I just had to alter the boostrap function in `main.js` (Intl.js is already pulled as a dependency):

```js
bootstrap(aurelia => {
    if (!global.Intl) {
        console.log('Intl not present')
        require.ensure([
            'intl',
            'intl/locale-data/jsonp/en.js'
        ], function (require) {
            require('intl');
            require('intl/locale-data/jsonp/en.js');
            boot(aurelia);
        });
    } else {
        boot(aurelia);
    }
});


function boot(aurelia) {
    aurelia.use
        .standardConfiguration()
        .developmentLogging()
        .plugin('aurelia-i18n', (instance) => {
            let language = navigator.language.split('-')[0];

            // register backend plugin
            instance.i18next.use(XHR);

            function loadLocales(url, options, callback, data) {
                switch (url) {
                    case 'en':
                        callback(enTranslations, { status: '200' });
                        break;
                    case 'fr':
                        callback(frTranslations, { status: '200' });
                        break;
                    default:
                        callback(null, { status: '404' });
                        break;
                }
            }

            instance.setup({
                backend: {
                    loadPath: '{{lng}}',
                    parse: (data) => data,
                    ajax: loadLocales,
                },
                lng: language,
                attributes: ['t', 'i18n'],
                fallbackLng: 'en',
                debug: false,
            });
        });

    aurelia.start().then(() => aurelia.setRoot('app', document.body));
}
```

**Comment by EisenbergEffect** [comment]
@zewa666 Do the docs contain a section on what browsers require polyfills? If not, we should add that.

**Comment by Jenselme** [comment]
@EisenbergEffect There is already a section in the documentation about Intl polyfill: https://github.com/aurelia/i18n#internationalization-api-polyfill but it doesn't detail how to use it in a bundle.

And I think that the message I got from Webpack is quite obscure. It took me a while to understand that the missing Intl API was the problem.

I think that maybe the code could be improved a little near [here](https://github.com/aurelia/i18n/blob/9142415eb1305d02a26ba8cad8d6816c04ddd61b/src/aurelia-i18n.js#L58): if the Intl API is not found, the plugin automatically try to load it. But in my case since it failed, I got this weird webpack error. Moreover since in case of bundling we have to think to include the polyfill, the user may forget it. A log message would be welcome to diagnose the problem.

**Comment by zewa666** [comment]
@Jenselme I'm happily accepting a PR adding those mentioned console logs and information. This would definitely help to improve the error and thus point the user to the proper implementation.

**Comment by khenderick** [comment]
@zewa666 is this ```bootstrap``` function still something that exists in Aurelia? All examples all over the web are talking about the usual ```configure```, but I'm not sure how this translate into this ```bootstrap``` function. If this piece of docs is outdated, I'd like to find out how to properly detect and load the polyfill and open a PR to update it.

**Comment by zewa666** [comment]
bootstrap is indicating the use of a manual bootstrapping process. Take a look at the [docs here](http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/app-configuration-and-startup/4). If you feel like the information is too sparse we'll happily accept PRs
