### ISSUE TITLE
 Error looking up github:i18next/i18next@^1.9.0.

### ISSUE THREAD

**Issue by suneelv** [aurelia/i18n#71]
When trying to install this plugin using "jspm install aurelia-18n, I am getting the following error

 Error looking up github:i18next/i18next@^1.9.0 and the installation is failing.

**Comment by suneelv** [comment]
Using jspm install aurelia-i18n@^0.4.10 is working

**Comment by ggrimbert** [comment]
I am experiencing a problem too, I got 
```
err  Repo npm:i18next/i18next not found!
```
while trying  
```
jspm install aurelia-i18n@^0.4.10
```

**Comment by droda59** [comment]
Same, doesn't work for me with any version

**Comment by RomkeVdMeulen** [comment]
Same here. Installation over npm is working, jspm gives `Repo npm:i18next/i18next not found!`

**Comment by zewa666** [comment]
ok so this problem can only happen with a newer version of jspm.
the thing is that the old < v.2 releases of i18next are a bit weird and need to be installed via github. It seems that JSPM > 0.16.15 allthough has issues with differentiating between github/npm sources.

So can you all please try the following inside your project if your global jspm version <> 0.16.15 (check that out by running `jspm -v`)
1. delete jspm folder
2. delete npm folder
3. run `npm install jspm@0.16.15`
4. run `npm install`
5. run `jspm install`

and now check out whether it works

**Comment by droda59** [comment]
Works for me doing that

**Comment by zewa666** [comment]
I've started work on a new branch to include i18next v2.
https://github.com/aurelia/i18n/tree/update-i18next

I'd like to ask everybody to give this a try and see whether that throws any install errors from either NPM or JSPM. Also try installing the --DEV envs and run the karma tests

**Comment by doktordirk** [comment]
@zewa666 what's the target jspm? 16.15, 16.30, 17beta or all of the above?

**Comment by zewa666** [comment]
tbh I've just tried it with v 0.16.15, but since npm destinations are now used for all parts it should also work with .17 and .30 as those where the missing points as far as I can remember.

In the meantime I've also updated the readme of the branch to show how to install a backend plugin (XHR for the demo) inside the skelly and use it.

**Comment by doktordirk** [comment]
*had no problem building/testing the repo with .31
*had no problem installing with .15 or .31

**Comment by zewa666** [comment]
fantabulous :+1: 

if you're interested in giving it a try via the skelly just run `jspm link` inside the aurelia-i18n folder and `jspm install --link npm:aurelia-i18next` inside the skelly folder. Respecting the new settings mentioned in the README should get you going quickly

**Comment by doktordirk** [comment]
or use 
`jspm install aurelia-i18n=github:aurelia/i18n@update-i18next`

**Comment by zewa666** [comment]
Closing this one due to i18next version upgrade
