### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'new this.Intl.DateTimeFormat')

### ISSUE THREAD

**Issue by mbenedyk** [aurelia/i18n#76]
I get exception
"TypeError: undefined is not an object (evaluating 'new this.Intl.DateTimeFormat')"
 when i execute unit test for 'df' by Chutzpah, but when i run them from browser they are ok

I`m using aurelia-i18n@0.4.10

probably refers to: https://github.com/aurelia/i18n/issues/52

**Comment by zewa666** [comment]
oh ok didn't see earlier that you already created a new issue :)

ok lets see if the next release by @EisenbergEffect will fix this otherwise we need to take a closer look.

**Comment by zewa666** [comment]
@mbenedyk whats the status on this one after the latest release?

**Comment by mbenedyk** [comment]
I`ll check it tomorrow

**Comment by mbenedyk** [comment]
Same problem:
TypeError: undefined is not an object (evaluating 'new this.Intl.DateTimeFormat')

**Comment by zewa666** [comment]
I don't know how Chutzpah works, what browser does it use to perform the tests? Chrome, or a headless one? Does that browser include the Intl API? Seems like the polyfill is not loaded in your case. Over here I'm testing with Karma and Chrome and so far everything works.

**Comment by EisenbergEffect** [comment]
Closing this since it's likely a missing polyfill in the test environment and there's been no response from the OP in over a month.
