### ISSUE TITLE
Set innerHTML within TValueConverter & TBindingBehavior

### ISSUE THREAD

**Issue by stefan505** [aurelia/i18n#77]
Is it possible to set the innerHTML similar to `[html]` used on attributes within TValueConverter and TBindingBehavior?

```
<span>${ '[html]name' | t: {'name': i18n_params.name}}</span>
```

The above doesn't work.

**Comment by zewa666** [comment]
No not really ... this mode is more for simple renamings text but not full fledged solutions possible with the attributes

**Comment by stefan505** [comment]
Bummer, thanks.
