### ISSUE TITLE
issue with typescript compliling

### ISSUE THREAD

**Issue by geea789** [aurelia/i18n#78]
anyone any idea how to fix this warning? (i get this while serving gulp - compiling typescript)

/jspm_packages/github/i18next/i18next@1.11.2/typescript/lib/jquery.d.ts(3190,13): Subsequent variable declarations must have the same type.  Variable '$' must be of type 'cssSelectorHelper', but here has type 'JQueryStatic'."

**Comment by zewa666** [comment]
phew good question, sounds like a bug in the jquery typing. Wonder whether this is just specific to that version or it got fixed in the meantime.

Nevertheless it's not related to Aurelia directly

**Comment by zewa666** [comment]
Closing this as it not really belongs to Aurelias plugin itself.
