### ISSUE TITLE
Setup d.ts generation

### ISSUE THREAD

**Issue by EisenbergEffect** [aurelia/i18n#8]
Be sure that d.ts files are being generated from the source using our babel plugin. You can see how to set this up by looking at the build tasks from any core repo. Along with this, set up the doc generation. This can be seen by looking at the doc task from any core repo. Setting up the docs along side this will ensure that the generated d.ts files are correct because the docs infrastructure uses the TS compiler to validate the generated d.ts when generating the docs.

**Comment by zewa666** [comment]
@EisenbergEffect ok will do so just need some free time to do the type annotations

**Comment by zewa666** [comment]
@EisenbergEffect could you please check the configs from the branch https://github.com/aurelia/i18n/tree/dts-setup? Running `gulp build` currently errors with multiple declarations of `import i18n`

**Comment by EisenbergEffect** [comment]
@zewa666 Can you make sure that aurelia-tools is up to date in this repo and then try building the d.ts again? That may be why you are seeing that issue.

**Comment by zewa666** [comment]
@EisenbergEffect hey as discussed with you while being in Tally, could you setup the necessary stuff you mentioned in order to get me started with creating the dts file?
