### ISSUE TITLE
Cannot find modules t, nf, df and rt with webpack

### ISSUE THREAD

**Issue by Jenselme** [aurelia/i18n#84]
While trying to see if the problem I had [here](https://github.com/aurelia/i18n/issues/46#issuecomment-199848329) comes from i18next or aurelia-i18n, I tried to do a sample app with the latest webpack skeleton. When I added the i18n plugin, I have this error:

```
.*$:106 Uncaught (in promise) Error: Cannot find module './aurelia-i18n/t'.
.*$:106 Uncaught (in promise) Error: Cannot find module './aurelia-i18n/nf'.
.*$:106 Uncaught (in promise) Error: Cannot find module './aurelia-i18n/df'.
Uncaught (in promise) Error: Cannot find module './aurelia-i18n/rt'.
```

Any ideas where that comes from? You can find the full application (zip file) [here](http://jenselme.perso.centrale-marseille.fr/visible/skeleton-es2016-webpack.zip)

**Comment by EisenbergEffect** [comment]
It seems like this could be a submodules issue. See this comment: https://github.com/aurelia/validation/issues/226#issuecomment-202743716 Let me know if that helps.

**Comment by Jenselme** [comment]
It does. The plugin now works as expected. Maybe it should be mentioned in the documentation?

**Comment by EisenbergEffect** [comment]
@Jenselme I agree. Would you be interested in contributing to our docs? You would just need to sign our CLA and make a pull request :) We'd love to have you as a contributor.

**Comment by Jenselme** [comment]
> Would you be interested in contributing to our docs?

I certainly am. I'll try to do this by the end of the week.
