### ISSUE TITLE
Translations trying to solve keys before json is loaded

### ISSUE THREAD

**Issue by bellstrand** [aurelia/i18n#86]
After updating to v0.5.0, the plugin tries to solve translation keys before the translation files have been loaded when bundling the application.

i18next::translator: missingKey en translation xxx xxx

before we solved the problem with "getAsync: false;" (which now has been removed).
how can we let the translations wait untill our files are loaded with i18next v2?

The problem only occurs when bundling.

Could fix a repo showing the problem if that would help?

**Comment by periclitor** [comment]
I also noticed the same problem yesterday, only when bundling and exporting. What should be bundled and what should be added in the export as static files. What about i18next-xhr-backend?

**Comment by bellstrand** [comment]
Untill we find a proper solution i made it work with a temporary fix like this:

```javascript
import XHR from 'i18next-xhr-backend';

export function configure(aurelia) {
	aurelia.use
		.standardConfiguration()
		.plugin('aurelia-i18n', instance => {
			instance.i18next.use(XHR);
			instance.setup({
				backend: {
					loadPath: '/locale/{{lng}}/{{ns}}.json'
				},
				ns: ['translation'],
				lng: 'en',
				attributes: ['t', 'i18n'],
				fallbackLng: 'en',
				debug: false
			}).then(() => {
				aurelia.setupI18NFinished = true;
				setRoot(aurelia);
			});
		});

	aurelia.start().then(() => {
		aurelia.setupAureliaFinished = true;
		setRoot(aurelia)
	});
}

function setRoot(aurelia) {
	if(aurelia.setupAureliaFinished && aurelia.setupI18NFinished) {
		aurelia.setRoot();
	}
}
```

It adds a 5-10ms delay before aurelia.setRoot() gets called for me (running on a remote host on the local network), so i can live with it for now, but would be nice if we had a proper way to address this.

**Comment by tuath** [comment]
This looks like the problem I am running into...

**Comment by periclitor** [comment]
The workaround mentioned in #85 Namespace issues, solved my issue.

**Comment by jadrake75** [comment]
Makes sense it is related to bundling.  I was not seeing this on my dev laptop, but started seeing it when I deployed to my server.  Well at least it shows me text I was too lazy to externalize!   

Note: refreshing the page seems to resolve it (likely caching of the files by the browser).  I will implement the workarounds.

![i18n-messedup](https://cloud.githubusercontent.com/assets/3221886/14230830/78d7374c-f937-11e5-8535-67deee4955e9.png)

**Comment by Jenselme** [comment]
I think I have the same issue with 0.5.0. I found a workaround: downgrade i18next 2.4.x to 2.3.5. From what I understand, 2.4.0 introduced a 10ms timeout before actually loading the resources that prevented aurelia-i18n to work properly.

I fixed my issue with PR #92

**Comment by zewa666** [comment]
@bellstrand can you check whether the latest version has fixed this?

**Comment by bellstrand** [comment]
@zewa666 my problems are gone since 5.1! :+1:

**Comment by AdamWillden** [comment]
@zewa666 I don't understand but I'm having this same issue with 0.5.2

![image](https://cloud.githubusercontent.com/assets/4629144/14891804/24b54108-0d60-11e6-9b78-d12a02197d37.png)

**Comment by zewa666** [comment]
@AdamWillden you should take a look here https://github.com/aurelia/i18n/issues/93

**Comment by AdamWillden** [comment]
@zewa666 Thank you! I had read that but when you pointed me to it I knew I must have missed something ...and this is the info that I was missing: https://github.com/aurelia/i18n/commit/7cfb404eaa64d20b0992715e6f226e114933f81d#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by zewa666** [comment]
I wonder whether we can intercept that error/warning and add our custom message to inform the user about a potentially missing returned promise
