### ISSUE TITLE
Configuration of Backend with IIS Application

### ISSUE THREAD

**Issue by crabulik** [aurelia/i18n#88]
Hi all!
I'm trying to use Aurelia with ASP.Net core with hosting on IIS.
My issue with localization is:

I need to host web application on on Sub application of my IIS Web Site. 
When I execute the application with using 'localhost' instead of server IP it looks fine. But when i execute the application with using Server IP, I18next XHR tries to load languages from wrong URL.
It tries to get localization files from "http://X.X.X.X/locales/en-GB/translation.json" instead of "http://X.X.X.X/ApplicationName/locales/en-GB/translation.json".

My XHR backend configuration is:

backend: {
    loadPath: '/locales/{{lng}}/{{ns}}.json'
}

Thanks.

Version: aurelia-i18n@^0.5.0

**Comment by zewa666** [comment]
Sounds like something related specifically to the xhr backend config.
I think it's the best to ask i18next specific question directly in their respective repos in order to get the best help.

**Comment by crabulik** [comment]
@zewa666 thnx!

Is there any way to pass the cofiguration, which was loaded by "aurelia-configuration" to confuguration function "aurelia-i18n"? It may help to set correct path in the configuration file.

**Comment by masterpoi** [comment]
Doing something similar but without the leading slash. Did you try:
backend: {
loadPath: 'locales/{{lng}}/{{ns}}.json'
}

?

**Comment by crabulik** [comment]
@masterpoi 
Such configuration hepled me:
backend: {
loadPath: './locales/{{lng}}/{{ns}}.json'
}

**Comment by zewa666** [comment]
I guess this is fixed with your last reply @crabulik right? Closing this for now, lets reopen if still issues exist

**Comment by crabulik** [comment]
@zewa666 Yeap, i think it works fine.
