### ISSUE TITLE
Using typescript-webpack

### ISSUE THREAD

**Issue by mttmccb** [aurelia/i18n#89]
I'm struggling to get this working with the latest typescript-webpack skeleton, the main one being

    (4,17): error TS2307: Cannot find module 'i18next-xhr-backend'.

Is there anything special I need to do with the webpack.config.js file? The only change I've made was to include a submodule

    plugins: [
      new AureliaWebpackPlugin({
        includeSubModules: [
                { moduleId: "aurelia-i18n" }
            ]
      })
    ],

**Comment by mttmccb** [comment]
This might be just due to a lack of .d.ts I'll post what I did later, it didn't solve all my problems but at least it compiles

**Comment by Jenselme** [comment]
I think you need to add `i18next-xhr-backend` as a dependency to you package.json and configure i18next to use the XHR backend as described [in the doc](https://github.com/aurelia/i18n#how-to-install-this-plugin). See point 7.

**Comment by mttmccb** [comment]
Thanks @Jenselme I did both of those but that didn't resolve it. I ended up creating my own typing for `i18next-xhr-backend` so it at least compiles.

**Comment by emiba** [comment]
I have the same error for the non webpack typescript skeleton project.

**Comment by mttmccb** [comment]
about as basic as it gets...

    declare module 'i18next-xhr-backend' {
        export class XHR {
        }
    }

**Comment by zewa666** [comment]
Is this maybe related to https://github.com/aurelia/i18n/issues/99?

**Comment by olehleskiv** [comment]
Have the same issue. There is no (d.ts.) typings for i18next-xhr-backend. Can somebody add them?

**Comment by mttmccb** [comment]
Yes and no, it's because the typing file is missing and I had to use the default import syntax otherwise it failed.

**Comment by zewa666** [comment]
yep but I think as mentioned over there the default export is **Backend**  vs. **XHR**, so I thought that would maybe fix it at least so far that it doesn't completely break.

Nevertheless, I think we should really go for asking the creator of the backend to provide a valid d.ts file in order to fully solve that. So I'll be closing this here for now, we can reopen if there are more issues to it.

**Comment by leye0** [comment]
Can we keep it as a references while waiting?
`
declare module 'i18next-xhr-backend' {

    interface Interpolator {
        interpolate: () => string
    }
    interface Services {
        interpolator: Interpolator
    }
    export default class Backend {
        type: 'backend';
        services: Services;
        options: {
            loadPath: string,
            addPath:  string,
            allowMultiLoading: boolean,
            parse: () => {},
            crossDomain: boolean,
            ajax: () => void
        };
        constructor(services: Services, options?: {});
        init(services: Services, options?: {}): void;
        readMulti(languages: any[], namespaces: any[], callback: () => void): void;
        read(language: {}, namespace: {}, callback: () => void): void;
        loadUrl(url: string, callback: () => void): void;
        create(languages: any[], namespace: string, key: string, fallbackValue: string): void;
    }
}
`
