### ISSUE TITLE
how to wait for translation load?

### ISSUE THREAD

**Issue by Leonidnei** [aurelia/i18n#93]
Hi.

We use i18n.tr(code) in VM constructor of the first page.
The result sometimes comes correct but sometimes it returns the code without translation.
I suspect that i18next backend reads the file asynchronously and sometimes the constructor is invoked before the translation file is loaded.

If so, any idea how to wait for this load to occur before calling tr?

**Comment by Leonidnei** [comment]
I've understood that option "  getAsync: false," does not exist anymore. Is there something replacing it?

**Comment by bellstrand** [comment]
#86 #85, you have a couple of "workaround" there, and a fix have been merged into the repository, think we're just waiting for a new release now?

**Comment by Leonidnei** [comment]
I bypassed the problem by adding await for instance.setup

**Comment by zewa666** [comment]
exactly, methods like setup and setLocale will return a promise which when fulfilled should guarantee that the translation is loaded. Closing this for now, we can reopen if there are still some issues
