### ISSUE TITLE
TValueConverter and TBindingBehavior not working when using Webpack

### ISSUE THREAD

**Issue by valichek** [aurelia/i18n#94]
No errors in console.

translation.json:
```json
{"locale-name": "de-DE"}
```
template:
```html
<span t="locale-name"></span> <span>${'locale-name' | t}</span> <span>${'locale-name' & t}</span>
```
results to:
```
de-DE locale-name locale-name
```

main.js:
```javascript
var Promise = require('bluebird'); // Promise polyfill for IE11
import {bootstrap} from 'aurelia-bootstrapper-webpack';

import {I18N} from 'aurelia-i18n';
import XHR from 'i18next-xhr-backend';

function loadLocales(url, options, callback, data) {
  try {
    let waitForLocale = require('bundle!json!../locale/'+url+'.json');
    waitForLocale((locale) => {
      callback(locale, {status: '200'});
    })
  } catch (e) {
    callback(null, {status: '404'});
  }
}

bootstrap(function(aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('aurelia-i18n', (instance) => {
        // register backend plugin
        instance.i18next.use(XHR);

        // adapt options to your needs (see http://i18next.com/docs/options/)
        instance.setup({
          backend: {                                  // <-- configure backend settings
            //loadPath: '/locale/{{lng}}/{{ns}}.json' // <-- XHR settings for where to get the files from
            loadPath: '{{lng}}/{{ns}}',
            parse: (data) => data,
            ajax: loadLocales
          },
          lng : 'de',
          attributes : ['t','i18n'],
          fallbackLng : 'en',
          debug : false,
          //compatibilityJSON: 'v1',
          ns: ['translation','nav', 'secuident']
        });
      });

  aurelia.start().then(() => aurelia.setRoot('app-webpack', document.body));
});
```

**Comment by zewa666** [comment]
does that relate somehow to this? https://github.com/aurelia/i18n/pull/91

**Comment by valichek** [comment]
@zewa666, no errors described in #91, and no errors that are usually are thrown when ValueConverter or BindingBehaviour not found when you have smth like `${'smth' | notExistingValueConverter}`

**Comment by valichek** [comment]
@zewa666 like it loads resources after calling i18next.t from TValueConverter and TBindingBehavior, any ideas how to fix it?

**Comment by valichek** [comment]
Ok, so fixed that, I think docs should be updated. Here is how initialization should look like, we just return promise we get from `instance.setup(...)` in plugin configuration.
```
aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('aurelia-i18n', (instance) => {
        // register backend plugin
        instance.i18next.use(XHR);

        // adapt options to your needs (see http://i18next.com/docs/options/)
        return instance.setup({
          backend: {                                  // <-- configure backend settings
            //loadPath: '/locale/{{lng}}/{{ns}}.json' // <-- XHR settings for where to get the files from
            loadPath: '{{lng}}/{{ns}}',
            parse: (data) => data,
            ajax: loadLocales
          },
          lng : 'de',
          attributes : ['t','i18n'],
          fallbackLng : 'en',
          debug : false,
          //compatibilityJSON: 'v1',
          ns: ['translation','nav', 'secuident']
        });
      });
```

**Comment by zewa666** [comment]
@valichek thanks for looking into this, I did not have the chance to look at it yet. Good point, I've updated the readme to reflect your findings. I'll be closing this for now, lets reopen if we experience further issues

**Comment by avizcaino-newuibcn** [comment]
Not sure if it is related with this issue, but I'm having a similar behavior even after adding the return of the instance.setup.

```
return instance.setup({
        backend:{
          loadPath: '{{lng}}/{{ns}}',
          ajax: loadLocales,
          parse: (data) => {
            return data;
          }
        },
        lng: 'dev',
        attributes: ['t', 'i18n'],
        fallbackLng : 'en',
        debug: true,
        ns: ['translation']
      });
```

The literals are not translated and the console is returning this: 

```
i18next::translator: missingKey dev translation launcher-all-label launcher-all-label
logger.js:24 
```

**Comment by valichek** [comment]
@avizcaino-newuibcn so you can check in the log if `i18next::translator: missingKey dev translation launcher-all-label launcher-all-label` appears before resources loaded

**Comment by avizcaino-newuibcn** [comment]
@valichek yep, thats the problem. My app is rendering before the resources are loaded and is not able to find the translation keys...

**Comment by valichek** [comment]
@avizcaino-newuibcn maybe you haven't updated to latest versions all the aurelia stuff

**Comment by avizcaino-newuibcn** [comment]
I've checked and i'm using the last release...
El dia 15/04/2016 13:41, Valiantsin Luchko <notifications@github.com> va escriure:@avizcaino-newuibcn maybe you haven't updated to latest versions all the aurelia stuff

**Comment by valichek** [comment]
@avizcaino-newuibcn And when you switch to other page and back it gets translated, does it? Could you prepare some basic example forked from aurelia-skeleton?

**Comment by avizcaino-newuibcn** [comment]
That's exactly what is happening! I'll try to prepare something
El dia 16/04/2016 21:47, Valiantsin Luchko <notifications@github.com> va escriure:@avizcaino-newuibcn And when you switch to other page and back it gets translated, does it? Could you prepare some basic example forked from aurelia-skeleton?
