### ISSUE TITLE
Error loading "./intl" module with Webpack (safari)

### ISSUE THREAD

**Issue by TGMorais** [aurelia/i18n#98]
Hi, I this might be related to this https://github.com/aurelia/i18n/issues/61, but there is no information there on how to solve it, at least not with webpack.

The plugin is throwing an error when trying to load the intl polyfill  (in per ex, safari)

I just used the fresh webpack-skeleton and installed the plugin
`npm install aurelia-i18n --save` 

then configured `webpack.config.js` with
```
 new AureliaWebpackPlugin({
      includeSubModules: [
        { moduleId: "aurelia-i18n" }
      ]
    }),
```

and included the plugin
```
    .plugin('aurelia-i18n', instance => {
      return instance.setup({
          backend: {                                  // <-- configure backend settings
            loadPath: '/locales/{{lng}}/{{ns}}.json', // <-- XHR settings for where to get the files from
          },
          lng : 'de',
          attributes : ['t','i18n'],
          fallbackLng : 'en',
          debug : false
        });
    })
```
When I run `npm run dev`, it runs fine on browsers that support intl api on browsers that don't, it's failing to load the polyfill.

`"Cannot find module './intl'."`

Any ideas?
Thanks!

**Comment by EisenbergEffect** [comment]
There's not a strong reference to intl because it is only loaded when needed. This works fine with a real module loader, but not so much with webpack, which is only a bundler and requires it to be in the bundle. I'm not a webpack expert, but you will need to somehow tell it to include intl in the bundle.
