### ISSUE TITLE
Wrong import from i18next-xhr-backend in docs?

### ISSUE THREAD

**Issue by suneelv** [aurelia/i18n#99]
In How to Install This Plugin section, Step 7 has

import {I18N} from 'aurelia-i18n';
import XHR from 'i18next-xhr-backend'; 

But i18next-xhr-backend doesn't export XHR.
It is exporting Backend

The docs only work when we import Backend instead of XHR

**Comment by zewa666** [comment]
funny enough using the ES6 demo it still worked even with XHR. Nevertheless i've updated the docs as proposed. Thanks for the hint.
